openshift/machine-api-operator

pkg/render/render_test.go

Fixes https://jira.coreos.com/browse/CLOUD-91

Add unit tests for cluster and machine-set manifests

---

README.md

DO NOT USE ROOT.

---

OWNERS

Adding myself to the `OWNERS` file.

Add bison to OWNERS file

---

machines/aws/machine-set.yaml
pkg/render/config.go
pkg/render/render_test.go

Add ami filters so the actuator can get the right image

add machineSet ami filters

---

Makefile
hack/go-fmt.sh
hack/go-lint.sh
hack/go-vet.sh

Similar to https://github.com/openshift/cluster-api-provider-aws/pull/40

use redhat tooling image

---

lib/doc.go
lib/resourceapply/apiext.go
lib/resourceapply/apps.go
lib/resourceapply/clusterapi.go
lib/resourceapply/core.go
lib/resourceapply/rbac.go
lib/resourcemerge/apiext.go
lib/resourcemerge/apps.go
lib/resourcemerge/clusterapi.go
lib/resourcemerge/core.go
lib/resourcemerge/meta.go
lib/resourcemerge/meta_test.go
lib/resourcemerge/rbac.go
lib/resourceread/apiext.go
lib/resourceread/apps.go
lib/resourceread/clusterapi.go
lib/resourceread/core.go
lib/resourceread/rbac.go

add resource library, based on
https://github.com/openshift/machine-config-operator/tree/master/lib
https://github.com/openshift/library-go/tree/master/pkg/operator/resource

add resource library

---

manifests/clusterapi-controller.yaml

add version to aws-actuator image

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/sync.go
pkg/render/render.go

add operator pkg for reconciling logic

add operator pkg for reconciling

---

hack/yaml-lint.sh
machines/aws/machine-set.yaml
pkg/render/render_test.go

We've been using the wrong IAM profile here.

Use correct IAM profile for worker machines

---

Makefile

Separate linters and use `hack/go-vet.sh` in `make vet` stage

clean makefile

---

cmd/nodelink-controller/main.go

Propagete node role through machine spec label

---

Makefile

Is anybody reading this output?

Makefile: drop verbose flag on go build

---

install/0000_50_machine-api-operator_03_deployment.yaml

drop pull secret as this is not needed to download the operator image

drop pull secret

---

owned-manifests/clusterapi-manager-controllers.yaml

SSIA
Fixes: https://github.com/openshift/machine-api-operator/issues/107

Switch logrus to glog

---

pkg/operator/operator.go

return err from getProviderControllerFromImages

---

pkg/operator/operator.go
pkg/operator/sync.go
test/e2e/main.go
test/e2e/operator_expectations.go

Move syncClusterAPIController to report status conditions accordingly
Add operator status condition test

Add operator status condition test

---

cmd/machine-healthcheck/main.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

introduce remediation logic:
- if machine belongs to healthCheck CRD then remediate
- Remediate:
- if it is master skip
- if is not owned by a machineSet skip
- if it is recently unhealthy requeue
- if it is unhealthy for too long delete

introduce remediation

---

test/e2e/main.go
test/e2e/operator_expectations.go

Add ExpectAllMachinesLinkedToANode test
Needs https://github.com/openshift/machine-api-operator/pull/123

Nodelinktest

---

test/e2e/main.go
test/e2e/operator_expectations.go

ExpectReconcileControllersDeployment:
- get deployment
- delete deployment
- verify deployment is recreated

Expect reconcile

---

install/0000_50_machine-api-operator_08_deployment.yaml
test/integration/manifests/operator-deployment.yaml

Rename config path

---

test/e2e/operator_expectations.go

If for any reason a machine does not have a linked node the test should validatenodeRef is nil and legitimately fail

Ensure test wait for all machines to become nodes

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1654586
Info formated print is invoked with Infof.

Fix formated info print

---

README.md

Just demonstrate what is needed to test the machine health-checking mechanism.

Document how to test the healthchecking mechanism

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

Update machinehealthcheck controller machine annotation

Update machinehealthcheck controller machine annotation

---

pkg/operator/status.go
pkg/operator/sync.go

The operator's syncStatus method has been setting a single condition
and removing others already present, but most components checking
status expect all three default conditions (Available, Progressing,
and Failing) to be present and set to either True or False.  This
changes the status reporting to report all three at once.

Set all expected ClusterOperator status conditions

---

install/0000_50_machine-api-operator_02_machine.crd.yaml
install/0000_50_machine-api-operator_03_machineset.crd.yaml
install/0000_50_machine-api-operator_04_machinedeployment.crd.yaml
install/0000_50_machine-api-operator_06_machineclass.crd.yaml

Syncing with https://github.com/kubernetes-sigs/cluster-api/pull/672

Update CRD with description

---

test/e2e/operator_expectations.go

test: say how many nodes and machines are actually expected

---

test/integration/manifests/machineset.yaml

Since this got in https://github.com/openshift/cluster-api-provider-aws/pull/155

Fix aws provider group/kind

---

OWNERS

Extend list of owners

---

install/0000_30_machine-api-operator_08_rbac.yaml

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1689529

Allow to list, watch and patch events

---

pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1691120

mao: add support for 'None' provider type

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

Introduce azure support

---

install/image-references

Drop azure from payload temporally until there's confirmation the ART image and distgit repo is built

Drop azure from payload temporally

---

install/image-references

Add back azure image to payload
Needs:
https://jira.coreos.com/browse/ART-541

Add back azure image to payload

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1695197

Update LastTransitionTime at OperatorStatus Condition

---

pkg/operator/operator.go

```
E0401 08:06:27.851998       1 event.go:259] Could not construct reference to: '&v1.ClusterOperator{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"machine-api", GenerateName:"", Namespace:"", SelfLink:"/apis/config.openshift.io/v1/clusteroperators/machine-api", UID:"0cfdf4cd-5455-11e9-a124-0adb1443898a", ResourceVersion:"656", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63689702787, loc:(*time.Location)(0x1d1cea0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1.ClusterOperatorSpec{}, …
```

Register ClusterOperator to properly generate event for the kind

---

OWNERS

SSIA
/assign @enxebre @ingvagabund

Remove myself from OWNERS file

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go

SSIA
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1705748

Provide richer description of machinehealthcheck type

---

cmd/machine-api-operator/start.go
pkg/operator/operator.go

Makes possible to unittest operator events by passing fake recorder to the operator.

Set operator controller recorder via variable

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

install: use creds-operator to create creds for MAO on Azure

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

Add GCP support

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

https://jira.coreos.com/browse/CLOUD-518

Add GCP credential support

---

config/prometheusrule.crd.yaml
config/servicemonitor.crd.yaml
kustomization.yaml

Add prometheus CRDs for kube testing assumed by operators to exist.
needed by https://github.com/openshift/cluster-autoscaler-operator/pull/110

Add prometheus CRDs for kube testing

---

pkg/controller/nodelink/nodelink_controller.go
pkg/controller/nodelink/nodelink_controller_test.go

Originally the logic for setting the nodeRef in a machine was split between the cluster-api node controller and opt-int external tooling that would set an annotation for the former controller to watch. There's no reason for this to keep leaving in two different places, furthermore the cluster-api node controller is deprecated. This PR unifies the current logic and behaviour in one single nodelink controller.
Counterpart PR https://github.com/openshift/cluster-api/pull/47
Note:
This PR is to unify and simplify current code in one single nodelink controller while maintaining current behaviour to simplify farther development and maintainability.
Once we promote MHC, we could decide we don't care about the machine controller taking care of recreating a machine if something out of band deletes …

Add updateNodeRef for node link controller

---

pkg/operator/operator_test.go

Problem was that the informer cache was not being ensured to be synced before running the tests.
```
E0705 08:14:52.443801    6362 sync.go:37] Error syncing cluster api controller: timed out waiting for the condition
--- FAIL: TestOperatorSync_NoOp (320.10s)
--- FAIL: TestOperatorSync_NoOp/AWS (300.07s)
operator_test.go:165: 
Error Trace:	operator_test.go:165
Error:      	Received unexpected error:
timed out waiting for the condition
Test:       	TestOperatorSync_NoOp/AWS
Messages:   	unexpected sync failure
operator_test.go:166: 
```

Fix flaking unit test TestOperatorSync_NoOp

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Append platform for all credentialRequest's naming for consistency

Append platform for all credentialRequest's naming for consistency

---

install/0000_90_machine-api-operator_04_alertrules.yaml
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

Add phase field to metrics

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Refactor Machine Health Check controller:
- Reconcile model by mhc resource and domain targets(mhc,machine,node)
- A target is unhealthy when:
- Node Meets unhealthy conditions criteria
- Machine has no nodeRef for longer than timeout
- Machine has nodeRef but node is not found
- Machine is in phase "Failed"
- Add unit tests for every existing function 
Follow up:
- Add short circuiting API support and logic
```
apiVersion: healthchecking.openshift.io/v1alpha1
kind: MachineHealthCheck
metadata:
name: example
namespace: openshift-machine-api
spec:
selector:
matchLabels:
machine.openshift.io/cluster-api-cluster: agl141019-mchm4
machine.openshift.io/cluster-api-machine-role: worker
machine.openshift.io/cluster-api-machine-type: worker
machine.openshift.io/cluster-api-machineset: …
```

Mhc refactor

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

bug 1764092: fix typo logging

---

config/machine-api-operator-deployment.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

https://github.com/openshift/origin/issues/24247#issuecomment-560412327

Add CPU requests to containers

---

pkg/apis/machine/register.go
pkg/apis/machine/v1beta1/register.go

Left over from https://github.com/openshift/machine-api-operator/pull/440

Fix package name

---

pkg/controller/vsphere/actuator.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Add support for deleting machines.
First call make the destroy request and return error to let reconcile happens and monitor the destroy task until success.

Vsphere delete

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Add support for emitting events into `machinehealthcheck` controller. This change adds ability for user to be notified about decisions (and failed remediation actions) health-checking logic is making and then act accordingly if required.

Add support for events into MHC controller

---

pkg/controller/machinehealthcheck/OWNERS

Removing myself so people are not blocked on reviews, et al.

pkg/controller/machinehealthcheck/OWNERS: remove frobware

---

README.md

Update readme to reflect controllers

Update readme to reflect controllers

---

install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml

BareMetalHost CRD now needs a new field to disable certificate checking
to be able to test RedFish deployments.

Bug 1801228: Update BareMetalHost CRD

---

OWNERS

Add myself to the owners file so that I can approve PRs on this repo

Add JoelSpeed as Owner

---

Dockerfile
Dockerfile.rhel7
Makefile
install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator_test.go

This PR enables vsphere back. We want to have it in 4.5 release

Bring vsphere back

---

OWNERS
pkg/controller/machinehealthcheck/OWNERS

Removing myself from the OWNERS file.

Remove bison from OWNERS file

---

docs/proposals/machine-disruption-budget-kpe.md

 proposals - summary had incorrect spelling

---

FAQ.md

The URL was giving a 404 due to two capitalization issues

FAQ: Fix URL to machine-instance-lifecycle.md

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Needed By: https://github.com/openshift/cluster-api-provider-aws/pull/318

Bug 1822200: Add ec2:DescribeDhcpOptions permission request

---

config/cluster-reader-rbac.yaml

Added cluster-reader rbac for machine CRDs

Bug 1796412: cluster-reader is unable to view machine resources

---

FAQ.md

this change adds a question describing the differences between these two
resources and when you would use them. also gives links to examples.
/kind documentation

add faq question about ClusterAutoscaler and MachineAutoscaler

---

pkg/apis/machine/v1beta1/machine_webhook_test.go

Add more test cases and refactor to match the Azure tests with the modifySpec style testing

Improve testing of AWS validation webhook

---

README.md

README.md: Link to Bugzilla "Cloud Compute"

---

pkg/controller/vsphere/actuator.go
pkg/controller/vsphere/actuator_test.go

This PR adds tests for events that are created by the actuator.

[vSphere] Add tests for machine events

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

This is a cherry-pick of #524 
/assign @JoelSpeed

[release-4.4] Bug 1816606: Allow Int in String within MHC MaxUnhealthy

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

Fix for offer selection
Add missing option to specify offer/image/sku for azure.

Bug 1845610: Windows VM MachineSet error on Azure

---

pkg/controller/vsphere/machine_scope_test.go

This PR introduces the usage of envtest for testing machine patch

[vSphere] Use envtest for testing machine patch

---

pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

Enable termination handler for GCP

Enable termination handler for GCP

---

pkg/controller/nodelink/nodelink_controller.go

Signed-off-by: Roy Golan <rgolan@redhat.com>

node-linker: fix log msg in the machine indexer

---

pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

Enable termination handler for Azure
https://github.com/openshift/cluster-api-actuator-pkg/pull/170
https://github.com/openshift/cluster-api-provider-azure/pull/145

Enable termination handler for Azure

---

install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml

This updates the BareMealHost CRD to use v1 of the CRD type to provide
pruning of unknown fields.

Bug 1854142: update baremetalhost crd to apiextensions.k8s.io/v1

---

pkg/metrics/metrics.go

Currently, mapi_machine_created_timestamp_seconds is always
collected from the MAO.  On some UPI clusters, machine objects
may be created, even though the machine-controller is not
running.  This results in alerting for machines that are
missing the phase 'Running'.
This commit changes the MAO to only collect metrics for
machines that have non-empty, non-nil phase.

Bug 1810443: Don't collect machine metrics if machine-controller not running

---

pkg/operator/sync_test.go
pkg/operator/webhook_configuration.go

Fix panic in `applyWebhook` if the server error occurs. Also, add tests to simulate server failure, and confirm the behavior is preserved.

Bug 1863810: - panic: "invalid memory address or nil pointer dereference" while resyncing

---

pkg/controller/vsphere/reconciler.go

Currently, some unknown condition can cause the
actuator to double create the clone task.  The
suspected reason is an eventual consistency problem
in the vSphere API which results in the task
object returned by the API as being nil immediately
after creation.
This commit ensures we only ever create a single
clone task.

Bug 1880110: vSphere: Fix double create

---

pkg/controller/vsphere/actuator.go

The vSphere provider is reliant upon creating
and storing a task ID to track the cloning of a
template.  Without the task ID, we have no
record of requesting a template to create a new
instance.
Currently, it appears that we may be racing
with the controller's client cache and getting
a stale object when reconciling after initially
creating the task.  Even though we successfully
patch the status object with the new task ID,
the next reconcile may be utilizing out-dated
information and result in a double-create.

Bug 1880110: vSphere: create requeue delay

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

Validate AWS instance tenancy in webhook

Validate AWS instance tenancy in webhook

---

install/0000_30_machine-api-operator_00_namespace.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml

This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.

Add IBM Cloud managed annotations to CVO manifests

---

docs/user/machine-api-operator-overview.md

Describe which components are located under MAO management, how the operator components are deployed by the CVO, and the ClusterOperator status conditions.

[OCPCLOUD-994] Add simple overview user document

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

- Minor code restructuring, to enable correct metric reporting

Bug 1890456: Cleanup and refactor vSphere metrics

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

Add warning when GovCloud and spot are enabled in Azure. Spot instances on the GovCloud are likely not supported.

Bug 1882608: Add warning when govcloud and spot are enabled in Azure

---

Makefile
README.md
docs/dev/hacking-guide.md
hack/ci-test.sh
hack/go-fmt.sh
hack/go-gen.sh
hack/go-lint.sh
hack/go-vet.sh
hack/goimports.sh
hack/gosec.sh
hack/imagebuilder.sh
hack/owner_reset.sh

Fixed broken Makefile targets.
Added script to fix permission issues.
Updated hacking-guide.

[OCPCLOUD-1066] Makefile fix 

---

pkg/operator/sync.go

Previously if one resource failed to reconcile mao would break the loop. Now it should try resyncing all resources and aggregate errors before failing and break the loop.

[OCPCLOUD-930]: Aggregate operator errors before failing to sync

---

pkg/controller/machineset/machineset_controller_test.go

This should ensure that when the manager is told to stop, we actually wait for it to stop before ending the current test.
This should prevent issues where the test cases overlap while running which has led to intermittent issues with old managers overlapping with new managers

Bug 1921892: Ensure manager stops before ending the test

---

cmd/machine-healthcheck/main.go

remove code

---

install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

Add resource limit to pods. This should prevent our pods from consuming too many resources.

Add resource limit to pods

---

install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

Revert resource limit for pods.

Bug 1938493: Revert "Add resource limit to pods"

---

pkg/controller/machine/controller.go

If the original conditions are just fetched directly from the machine, this is a reference to a slice. This slice can then be updated by updating the machine conditions. We need to instead have a copy, else the comparison later won't work.
Also, if we mark the condition true then call the actuator update, this can cause issues as the actuator may also patch the machine (eg for providerID). So this needs to come after.
Tested manually on AWS.

Bug 1910318: Ensure original conditions aren't mutated during reconcile

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Currently, in case of non functioning kubelet / powered off vm  - disks which was attached for pvs would be removed with machine.
Changes in this PR:
Detaching disks from vm before deletion in case if node unreachable for unknown reason, which prevents their deletion and allow storage controller to attach this disks to another node.
No actual check for kubernetes persistent volumes does not happen here, all disks which does not have _persistent_ disk type would be detached. PV's disks has _independent\_*_ disk type.
Some details and reproducing scenarios might be found in [1883993](https://bugzilla.redhat.com/show_bug.cgi?id=1883993)

Bug 1883993: vSphere, detach virtual disks before virtual machine destroy if node not available

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

Make sure the phase is always set before creation. 
Check if the phase is empty, set it to provisioned, requeue, and call Create() only when the phase is set. 
Based on: https://github.com/openshift/machine-api-operator/pull/793

Bug 1925276: Make sure phase is always set before creation

---

pkg/operator/baremetal_pod.go

This PR mounts the trusted CA bundle and injects the proxy environment variables into all of the baremetal pod containers.

[release-4.6] Bug 1916772: Inject the cluster-wide proxy environment variables in the baremetal pod

---

pkg/controller/vsphere/reconciler.go

Currently if vm cloning tasks finished with error it wont be reflected in status condition, also we do not distinguish tasks by type (clone/delete) during deletion procedure which leads to quite slow deletion procedure execution (basically stucks till clone task will not be cleaned up from vsphere).
Changes in this PR:
- Update provider status condition in case of clone task finished with error
- added check for task type in deletion procedure, proceed further if clone task was finished with error

Bug 1918101: Fix deleting for machine stucked in provisioning state on vSphere

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This should resolve the attached bug, but also enables the enhancement I've added in https://github.com/openshift/cluster-api-provider-aws/pull/410 to also additionally improve the behaviour around this area

Bug 1965080: Update AWS permissions to reflect requirements for load balancers

---

install/0000_30_machine-api-operator_12_clusteroperator.yaml

Add related objects to Cluster Operator.

[OCPCLOUD-1173] Add related objects to Cluster Operator

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

[release-4.7] Bug 1933586: Make sure phase is always set before creation

[release-4.7] Bug 1933586: Make sure phase is always set before creation

---

pkg/operator/operator.go
pkg/operator/sync.go
pkg/operator/sync_test.go

Currently, whenever the deployment is rolling out, we block the reconcile for up to 3 minutes. This is causing issues in tests where we delete the deployment to check that the operator rolls out the changes appropriately. Now, any other action during this period has to wait three minutes.
This has been causing issues for the validating webhook tests for a long term and increasing our overall flakiness.
It is also bad form to block reconciliation for minutes at a time, with this change, we requeue, which allows us to resync if other changes are made in the mean time, eg if someone were to change the deployment, and then change it again after we make an edit.

Rewrite rollout checks to requeue and not block reconciles

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

GCP CI runs are complaining about APIs not being enabled

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Bug 2022839: GCP CI runs are complaining about APIs not being enabled

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

This implements the conditions part of openshift/enhancements#862. Currently this is based off of #945, though I'm aiming to keep them separate to make the review easier.
For this PR, please focus review on the last commit only, the first two are from the base PR.
This PR adds two new conditions, `Drainable` and `Terminable` to a Machine which identify whether the machine has lifecycle hooks or not. When a lifecycle hook is present, it will report the hook name and the hook owner on the condition so that users can look to the owner for further information.
Eg. We expect in the future we will see `"Drain operation currently blocked by: [etcd-quorum-member:cluster-etcd-operator]"` blocking control plane machines for the majority of their lifecycle

[OCPCLOUD-1351] Implement conditions for Machine Deletion Hooks reporting

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator.go

Check that the administrator enabled the MAPO feature gate, and
replace the Openstack machine controller image with the MAPO
machine controller image.

Machine API Provider OpenStack Feature Gate

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This commit adds missing validations for the recently added osDisk properties: diskSettings.ephemeralStorageLocation and cachingType [1]
[1] https://github.com/openshift/api/pull/1054

Bug 2034563: validate azure ephemeral storage location and caching type

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

replaces stand in MAPO images with real ones

Bug 2033390: connect real MAPO images

---

README.md

Signed-off-by: thejasn <thn@redhat.com>

fix readme after migrating from cluster-api-provider-*

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Bump prometheus/client_golang to the newest release.

Bug 2067852: Bump prometheus/client_golang

---

install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go

- Bump up API dependency to include Nutanix types
- Add Nutanix CredentialsRequest
- Add image for Nutanix Machine API Provider

Add Nutanix Platform to Machine API Operator

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This permission is needed for https://github.com/openshift/machine-api-provider-aws/pull/32

Add DescribeRegions permission for aws controller

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

To allow users to delete their machines with invalid specs, we have to allow them to remove finalizers. In this case all other validations will be skipped even if machine's spec is incorrect.

Skip validation if we just remove the finalizer

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Abort clone if HW version is not supported.

Bug 2059338: Add template HW version detection during clone

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Bug 2105382: fix the Machine validation webhook for nutanix providerSpec
Add validation for fields: CredentialsSecret and UserDataSecret

Bug 2104642: fix the Machine validation webhook for nutanix providerSpec

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

this is a cherry-pick of #1034 and #1038 combined. i am bringing them into a single PR to help work around some ordering issues with the backports, the bugzillas, and the bots, with the goal of making this easier to review and merge.

[release-4.11] Bug 2105382: Add a validation webhook for Nutanix MachineProviderConfig

---

install/0000_30_machine-api-operator_00_namespace.yaml

Reverts openshift/machine-api-operator#1031

Bug 2110501: Revert "Bug 2101880: operator NS manifest: Set empty openshift.io/run-level"

---

pkg/controller/machine/controller.go

The metric has been being updated every time the Machine reconciles, this isn't particularly helpful and means the data isn't useful. To fix this, only update the metric when the phase has actually changed for a machine. This should make the data accurate

[OCPBUGS-380] Ensure the phase transition metric only updates when the phase changes

---

pkg/controller/machine/drain_controller.go
pkg/controller/machine/drain_controller_test.go

If we drain multiple control plane machines at once, we know there are conflicting PDBs (KCM, KAS, KS, OAS) that prevent the drain from going through.
For example, each of these has a PDB that allows at most one disruption, if machine A and machine B are control plane machines, and A has a KCM guard and the other does not, we cannot remove the KCM guard from A. Now suppose B has a KAS guard and the other does not, we cannot remove the KAS guard from B.
This creates a deadlock in the drain logic.
In theory this could happen for workloads as well if users create conflicting PDBs like this, however, in that case, the worker node pool is easy to expand. For control planes we are much more limited.
The solution is to make sure we only drain a single control plane machine at once, in this case …

Only drain a single control plane machine at once

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Related to bug: https://issues.redhat.com/browse/OCPBUGS-1018

Restrict creating Power VS machine with negative processor and memory

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

xref: [CCO-321](https://issues.redhat.com//browse/CCO-321)
* Enhancement proposal: https://github.com/openshift/enhancements/pull/1301
* Corresponding change for `machine-api-provider-azure`: https://github.com/openshift/machine-api-provider-azure/pull/55

CCO-321: Add service account name to Azure credentials request

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go
pkg/controller/vsphere/session/tag_ids_caching_client.go
pkg/controller/vsphere/session/test_ids_caching_client_test.go
pkg/controller/vsphere/util.go

creating it to see if it helps to test [early](https://github.com/openshift/machine-api-operator/pull/1057)  
Please provide inputs if time permits it is for - OCPBUGS-10719 , keeping it as draft only.
@elmiko @damdo @RadekManak @JoelSpeed

OCPBUGS-10719: [release-4.11] - manual cp #1057 - machines stuck in provisioned or provisioning

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This PR adds Azure Confidential VM and Trusted Launch for VMs machine webhook validations.
Related machine-api-provider-azure [PR](https://github.com/openshift/machine-api-provider-azure/pull/54).

MGMT-13630: Add Azure Confidential VM and TrustedLaunch for VMs webhook validations

---

pkg/controller/vsphere/reconciler.go

addressing [issue found](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1701/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1684343285335724032/artifacts/vsphere-e2e-operator/gather-extra/artifacts/pods/openshift-machine-api_machine-api-controllers-5fddd956f6-8mppq_machine-controller.log) when deleting a vSphere machine.  The issue is related to the IPAM types not being present when the associated feature gate isnt enabled.

OCPBUGS-16925: only attempt to remove finalizers if staticIPFeatureGateEnabled

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

xref: [OCPCLOUD-2014](https://issues.redhat.com//browse/OCPCLOUD-2014)
related CCO PR: https://github.com/openshift/cloud-credential-operator/pull/556

OCPCLOUD-2014: Switch Azure credentials request to use explicit permissions

---

pkg/controller/vsphere/reconciler.go

/cherry-pick release-4.14 release-4.13 release-4.12 release-4.11

OCPBUGS-18339: Use docs URL instead of KCS article

---

OWNERS_ALIASES

This is a PR to update the approvers/reviewers of the repo. Thanks!

NO-JIRA: Update OWNERS

---

pkg/controller/vsphere/reconciler.go

Manually cherry picking so as not to create a duplicate issue.

OCPBUGS-24047: Update reference URL

---

pkg/controller/vsphere/reconciler.go

Update URL after docs refactor.
Manual cherry-pick to avoid a duplicated Jira issue.

OCPBUGS-24277: Update reference URL

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-25735: Add Snyk file to exclude vendor directory on scan

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-25734: Add Snyk file to exclude vendor directory on scan

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-24998: Add Snyk file to exclude vendor directory on scan

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-25165: Add Snyk file to exclude vendor directory on scan

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

xref: [OCPBUGS-25193](https://issues.redhat.com/browse/OCPBUGS-25193)

OCPBUGS-25193: Add additional vnet join permission for Azure

---

pkg/util/machineset/util_test.go

Hello, this is a PR to add unit tests to the MAO to test the scale from zero functions. Thanks!

OCPCLOUD-2493: Add unit tests for the functions handling ScaleFromZero annotations

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

** Add the hyperdisk-balanced disk type for gcp machines. 
** Add the test to validate the new type.

CORS-3580: Add the hyperdisk-balanced disk type

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

** Add the hyperdisk-balanced disk type for gcp machines. 
** Add the test to validate the new type.

CORS-3648: Add the hyperdisk-balanced disk type

---

README.md
docs/dev/hacking-guide.md
docs/user/machine-api-operator-overview.md
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

Manual cherry-pick of #1333 
/jira cherry-pick OCPBUGS-51263

OCPBUGS-51370: Drop oVirt support

---

README.md
docs/dev/hacking-guide.md
docs/user/machine-api-operator-overview.md
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

OCPBUGS-52342: Drop oVirt support

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Manual cherry-pick of [52576](https://github.com/openshift/machine-api-operator/pull/1344)
@sunzhaohua2 @JoelSpeed @huali9 @damdo PTAL, when time permits.

OCPBUGS-53045:  add image/read permissions

---

test/e2e/vsphere/machines.go
test/e2e/vsphere/multi-nic.go

[OCPBUGS-55461](https://issues.redhat.com/browse/OCPBUGS-55461)
Reverts openshift/machine-api-operator#1358

OCPBUGS-55461: Revert "Added skip for when config not multi nic"

---

pkg/controller/machineset/controller.go

This change fixes a potential nil pointer error when failing to set the paused condition in the machineset controller.
It captures the name of the machineset before calling the update status function, where if there is a failure the machineset passed is set to nil.
It also properly handles the scenario where the update status returns a not found error.

OCPBUGS-55461: Fixes machineset paused condition nil pointer

---

test/e2e/vsphere/multi-nic.go

[SPLAT-2039](https://issues.redhat.com//browse/SPLAT-2039)
- Modified e2e tests to work with hybrid env scenarios

SPLAT-2039: Fixed test logic for hybrid env scenario

---

test/e2e/vsphere/multi-nic.go

OCPBUGS-58429
- Fixed vsphere multi-nic tests to scale down machienset and to make sure machine is destroyed at end of test
This will need to be ported back to 4.19

OCPBUGS-58429: Fixed test logic to wait for machines ready and clean up

---

test/e2e/util.go

[SPLAT-2381](https://issues.redhat.com//browse/SPLAT-2381)
- Modified e2e tests to generate machine and machineset names with cluster name prefixed in them
- Updated function documentation comments

SPLAT-2381: Fixed e2e test to generate machines with cluster name prefix

---

OWNERS_ALIASES

NO-JIRA: Update OWNERS_ALIASES
