README.md

Point users to `make` in README

---

Makefile

This allows to run image build without having docker (imagebuilder is required then).
To run it, just execute:
```sh
make image NO_DOCKER=1
```
/CC: @ingvagabund

add optional imagebuilder

---

Dockerfile
Makefile

looks like go install sometimes puts the binary under bin -> use go build
@paulfantom FYI

Copy the mao binary from the right directory

---

cmd/main.go
examples/machine-api-operator-config-aws.yaml
examples/machine-api-operator-config-libvirt.yaml
machines/aws/cluster.yaml
machines/aws/machine-set.yaml
machines/cluster.yaml
machines/libvirt/cluster.yaml
machines/libvirt/machine-set.yaml
machines/machine-set.yaml
manifests/clusterapi-controller.yaml
pkg/render/config.go
pkg/render/machine-api-operator-config.yaml
pkg/render/render.go
pkg/render/render_test.go

Follow up for https://github.com/openshift/machine-api-operator/pull/34
See https://github.com/enxebre/installer/blob/mao/modules/bootkube/manifests.tf#L92

Libvirt support

---

cmd/main.go
machines/cluster.yaml
machines/machine-set.yaml
manifests/clusterapi-controller.yaml
pkg/render/config.go
pkg/render/machine-api-operator-config.yaml
pkg/render/render_test.go

This allows to integrate the openshift actuator with mao and the installer:
- https://github.com/enxebre/installer/blob/mao/modules/bootkube/resources/manifests/mao-config.yaml#L3
- https://github.com/openshift/cluster-api-provider-aws/pull/35

add support for openshift actuator

---

machines/aws/machine-set.yaml
machines/libvirt/machine-set.yaml
pkg/render/render_test.go

Removed carried over harcoded key.This is making the installer PR tests fail https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_installer/119/pull-ci-origin-installer-e2e-aws/786/artifacts/e2e-aws/pods/

remove harcoded ssh key

---

cmd/main.go
examples/clusterapi-apiserver-certs.yaml
manifests/clusterapi-apiserver.yaml

This fixes the namespace on the request when creating the Cluster and
MachineSet objects to match the target namespace.  It also changes the
name of secret containing the TLS assets to match what the installer
is using.

Fix namespace when creating Cluster and MachineSet

---

machines/libvirt/cluster.yaml

This was breaking libvirt installs.

Fix typo in libvirt cluster template

---

manifests/clusterapi-controller.yaml
pkg/render/render_test.go

This is a temporary home for this image until we have it under the OpenShift org. This is better than our personal namespaces, and is required to merge the PR integrating with the installer.

Use libvirt actuator image from CoreOS Quay org

---

Makefile

This (presumably) should be hack/go-fmt.sh, not hack/verify-gofmt.sh
because the latter doesn't exist in the repo.

Makefile: fix call to go fmt check

---

cmd/nodelink-controller/main.go

Perform both node-machine matching and node role labelling inside the same controller.
Any machine (or machineset) is expected to set `sigs.k8s.io/cluster-api-node-role` annotation to `master`, `infra` or `compute`. Once done and a node joins the cluster it gets the role assigned.

Integrate node role labeling into the nodelink controller

---

Dockerfile

@enxebre as discussed let's put the `nodelink-controller` binary in the mao image so we can deploy it with the actuators.

Bake nodelink-controller into the mao docker image

---

install/image-references

Update api server to include addresses in status spec
We can drop this one this lands https://github.com/kubernetes-sigs/cluster-api/pull/494

update apisever image

---

cmd/machine-api-operator/main.go
install/machineapioperator_01_images.configmap.yaml
install/machineapioperator_02_deployment.yaml
install/machineapioperator_02_rbac.yaml
install/machineapioperator_03_deployment.yaml
pkg/operator/operator.go
pkg/render/render.go
tests/e2e/main.go
tests/e2e/manifests/images.configmap.yaml
tests/e2e/manifests/operator-deployment.yaml
tests/e2e/manifests/rbac.yaml

This is being done so that MAO can be run in its own namespace instead kube-system

Run MAO in its own namespace

---

machines/aws/worker.machineset.yaml
pkg/render/render_test.go

We've had this since 04253cb9 (#34), but we don't need direct access to the workers.  Folks who do need to SSH into them, or whatever, should be able to access them via the masters.
Or maybe I'm just missing something, and this is actually important?

machines/aws/worker.machineset: Drop pubicIp

---

owned-manifests/clusterapi-apiserver-role-binding.yaml

The `extension-apiserver-authentication-reader` must always be in the `kube-system` namespace because that is where the role is and that is where  the resources it wants access to are located.
I'm not sure if there's a bindata I need to update somewhere.
/assign @enxebre

fix rolebinding namespace

---

Makefile

Invoking the following:
$ make build DBG=1
$ make nodelink-controller DBG=1
$ make test-e2e DBG=1
will build the respective binaries with Go debug support. The build
rules for those three targets are now `go build $(GOGCFLAGS) ...`.
The default value for GOGCFLAGS is -gcflags=all="-N -l", assuming
GOGCFLAGS it not already set in your environment. "all" specifies that
the flags should be applied to all packages (and may rebuild existing
up to date packages); "-N" disables compiler optimisations and "-l"
prevents inlining.
So, to override the defaults:
$ make build DBG=1 GOGCFLAGS='-gcflags="-N -l"'

Makefile: add Go debug support for local binaries

---

owned-manifests/clusterapi-manager-cluster-role.yaml

Must for updating just machine status. Tested through https://github.com/openshift/cluster-api-actuator-pkg/pull/19.

Extend RBAC role with updating status subresource

---

cmd/nodelink-controller/main.go
install/0000_50_machine-api-operator_01_images.configmap.yaml
owned-manifests/clusterapi-manager-controllers.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator.go
tests/e2e/main.go
tests/e2e/manifests/images.configmap.yaml
tests/e2e/util.go

Includes the nodelink controller in the controllers manifests
Move the nodelink controller to glog: `--log-level is gone` and `--logtostderror=true` is used instead.

Nodelink controller

---

cmd/machine-api-operator/start.go
pkg/operator/operator.go
pkg/types/types.go

remove unused code:
- APIRegistration was needed for aggregated api server, we use CRDs now
- ClusterAPIClient was need for deploying owned machineSets. That’s instantiated by installer now

remove unused code

---

cmd/common/client_builder.go
cmd/common/controller_context.go
cmd/common/helpers.go
cmd/machine-api-operator/start.go
pkg/operator/operator.go

Remove unused clients and informers:
- No need for ctx.KubeInformerFactory.Core().V1().ConfigMaps() since only config is the one time provider got from installer config
- Remove old apiregistrationclientset and clusterapiclientset
Increase minResyncPeriod

Remove unused clients and informers

---

test/e2e/main.go
test/e2e/operator_expectations.go

This validates a worker machine gets deleted. The backed node is removed. A new machine comes up automatically. A new node comes up.
Needs https://github.com/openshift/machine-api-operator/pull/132 to pass integration to satisfy jenkins expectations

Add ExpectNewNodeWhenDeletingMachine

---

test/integration/manifests/machineset.yaml

Due to substitution of `yaml.Unmarshal` for `codec.DecodeProviderConfig` in [1], `aws.cluster.k8s.io/v1alpha1` is no longer supported.
[1] https://github.com/openshift/cluster-api-provider-aws/pull/114/files#diff-ff59ea1505d1c2206134802c4f0f8ff2R167

Fix machineset apiversion in tests from aws.cluster.k8s.io/v1alpha1 to awsproviderconfig.k8s.io/v1alpha1

---

test/integration/aws.go
test/integration/manifests/machineset.yaml

The tectonicClusterID tag is being replaced with openshiftClusterID in the installer. This change will use the new tag name.
/hold on https://github.com/openshift/installer/pull/817

replace tectonicClusterID tag with openshiftClusterID

---

install/0000_50_machine-api-operator_03_machineset.crd.yaml
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

Additionally print:
- Desired Replicas
- Current Replicas
- Ready Replicas
which is similar to the replicaset output.
If you're going to watch output then be wary of:
https://github.com/kubernetes/kubernetes/issues/66538

machineset: add additional printer columns to CRD

---

Dockerfile.rhel7

Update Dockerfile.rhel7 for machine healthchecks and manifests

Update Dockerfile.rhel7 for machine healthchecks and manifests

---

Makefile

Preload correct version number during build.
Fixes #145

use proper version number when building MAO

---

cmd/machine-api-operator/helpers.go

Currently leader election resource lock recorder uses empty scheme
that prevents to record leader election events under the config map.

Use non-empty scheme under the resource lock

---

cmd/nodelink-controller/main.go

Cluster-api upstream changed the node machine linking annotation to `cluster.k8s.io/machine`. We need to support both the old `machine` one and the current one until both aws and libvirt actuator update their deps and have the node controller consume `cluster.k8s.io/machine`.

Nodelink controller: check for both old and new machine annotation key

---

cmd/nodelink-controller/controller_test.go
cmd/nodelink-controller/main.go
test/e2e/main.go
test/e2e/operator_expectations.go

Sync taints from machine spec to the node in additive fashion

---

owned-manifests/clusterapi-manager-controllers.yaml

Let's enable this for the sake of better visibility, specially since we are introducing support for machine deployments

Add logtostderr flag for controller-manager

---

cmd/nodelink-controller/main.go
test/e2e/operator_expectations.go

Since we merge this upstream https://github.com/kubernetes-sigs/cluster-api/pull/593/files we needed to support both annotations for backwards compatibility. After aws/libvirt actuators including latest cluster-api, the old annotation can be removed. See https://github.com/openshift/cluster-api-provider-aws/pull/127 and https://github.com/openshift/cluster-api-provider-libvirt/pull/104

Remove deprecated machine annotation

---

Dockerfile
Dockerfile.rhel7
Makefile
hack/go-build.sh

Unify a way to build binaries. Previously binaries for containers were build in a different way than those for development which posed a problem (for example lack of mao version number when run from a container image). This bash wrapper solves those issues.
Wrapper is a slightly modified version of: https://github.com/openshift/machine-config-operator/blob/master/hack/build-go.sh

wrap binary building in a bash script

---

install/0000_50_machine-api-operator_02_machine.crd.yaml
install/0000_50_machine-api-operator_03_machineset.crd.yaml
install/0000_50_machine-api-operator_04_machinedeployment.crd.yaml
install/0000_50_machine-api-operator_06_machineclass.crd.yaml

cluster-api master has renamed `providerConfig` to `providerSpec`,
we must allign to this changes
**TODO**

Rename of providerConfig to providerSpec under CRD's

---

install/0000_50_machine-api-operator_02_machine.crd.yaml
install/0000_50_machine-api-operator_03_machineset.crd.yaml

This adds pretty printers when rendering tables in CLI.
Machines
```sh
oc get machines -n openshift-cluster-api
NAME                                 INSTANCE              STATE     TYPE       REGION      ZONE         AGE
decarr-dev-master-0                  i-0c5c6028992720b04   running   m4.large   us-east-2   us-east-2a   4h
```
MachineSets
```sh
oc get machinesets -n openshift-cluster-api
NAME                           DESIRED   CURRENT   READY     AVAILABLE   AGE
decarr-dev-worker-us-east-2a   1         1         1         1           4h
```

Add CLI printer columns for machine, machinesets

---

owned-manifests/clusterapi-manager-controllers.yaml

- Add back controllers using latest provider image so using machine.openshift.io https://github.com/openshift/cluster-api-provider-aws/pull/147
- We have now all controllers for `cluster.k8s.io` and `machine.openshift.io`

add back controllers using latest provider image so using machine.openshift.io

---

cmd/machine-api-operator/main.go
install/0000_30_machine-api-operator_00_namespace_cluster-api.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_13_rbac.yaml
install/0000_30_machine-api-operator_14_deployment.yaml
test/e2e/main.go
test/e2e/operator_expectations.go
test/integration/generate.sh
test/integration/main.go
test/integration/manifests/cluster.yaml
test/integration/manifests/ign-config.yaml
test/integration/manifests/images.configmap.yaml
test/integration/manifests/machineset.yaml
test/integration/manifests/operator-deployment.yaml
test/integration/manifests/rbac.yaml

Create openshift-machine-api namespace
Deploy components into openshift-machine-api namespace
Once this get merged we can update the namespace of the machines run by the installer https://github.com/openshift/installer/pull/1215

Deploy components into openshift-machine-api namespace

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
test/e2e/main.go
test/e2e/operator_expectations.go

dup of https://github.com/openshift/machine-api-operator/pull/203

Drop deprecated namespace from tests

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go
test/integration/main.go
test/integration/manifests/status-crd.yaml

Support for setting multiple operands in version dynamically
Stop setting `available=false` when `progressing`
Compare available (`status.Versions`) vs desired (`optr.Versions`)
Aligns with https://github.com/openshift/machine-config-operator/pull/351

Stop reporting unavailable when progressing and add support for multiple operands status

---

pkg/controller/machinehealthcheck/OWNERS

@beekhof @cynepco3hahue on CNV team are using the machine API Operator domain for building solutions for machine health checking on bare metal.

Adding new reviewers beekhof and cynepco3hahue for health check controller

---

install/0000_30_machine-api-operator_00_namespace_cluster-api.yaml

Since
https://github.com/openshift/installer/pull/1245/files and
https://github.com/openshift/installer/pull/1246/files#diff-a25ec653fe393c89c4ccac5a1edfe38fR56
This can be dropped now

Delete openshift-cluster-api namespace

---

test/e2e/main.go
test/e2e/operator_expectations.go

Since this [openshift/installer@37b25ea#diff-a25ec653fe393c89c4ccac5a1edfe38fL51](https://github.com/openshift/installer/commit/37b25ea64964ad0671e6f498b57646efe641ad6f#diff-a25ec653fe393c89c4ccac5a1edfe38fL51) got in the cluster obejct needs to exist however is circumstantial for the actuator and no need to validate it exist or not here. See https://jira.coreos.com/browse/CLOUD-357
https://github.com/openshift/cluster-api-provider-aws/pull/163

Remove cluster e2e test since it's not relevant for actuator

---

owned-manifests/clusterapi-manager-controllers.yaml

Updated resource requirements with following guidelines:
- components that run on master nodes should never specify cpu limits as they introduce latency even when there is no resource contention
- components that run on master nodes should specify cpu requests relative to other components.  in this case, i have updated to 10m which means your component will get 1/10th CPU time as kube-controller-manager when there is contention on the node (which is appropriate given fewer controllers).
- removed usage of memory limits in favor of normal kubelet and kernel driven response to memory exhaustion (oom killer targets containers whose memory usage is greatest relative to request)
Cleanup related to smoke testing efforts in origin here:
https://github.com/openshift/origin/pull/22095

manifests: update resource requirements

---

README.md

The sample command was missing the "start" sub-command.

README.md: Fix run command in dev section.

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This is not currently used by the actuators but does get used by
installer for pre-flight checking of permissions (soon). When ready to
start using your fine grained credential it will be defined here and
under your control.

Add AWS credentials request.

---

install/0000_30_machine-api-operator_08_rbac.yaml

This is required by the cluster-api-provider-openstack so it can create a secret containing a token that is used in the boot process. This secret is passed to the `userData` render step, which is a bit different from the way the `AWS` actuator does things.
I'm working with upstream to improve this requirement but it also feels like a sane default permission to have for this service account.

Allow for the openshift-api-manager role to create secrets

---

install/0000_30_machine-api-operator_09_deployment.yaml

As of now, machine-api-operator doesn't have `system-node-critical` priority, the pods created for this deployment may get evicted by scheduler, if this priorityClass is not available. The rationale behind adding `system-node-critical` is we have nodeSelector to ensure that we are running on master nodes.

Add cluster-critical priorityClass to machine-api

---

install/0000_30_machine-api-operator_09_deployment.yaml

do not set limits for the operator per no component that runs on masters should use limits.
update cpu requests to 10m align with other operators.

machine-api-operator should not set limits

---

cmd/machine-api-operator/helpers.go
cmd/machine-api-operator/start.go
cmd/nodelink-controller/main.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

Improve logging and add events for the operator cluster status
Conventions:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
- if an error message is just printed, use uppercase
- if an error message is return by a function/method and passed on, use lowercase
- NOUN VERB STATE format when possible

Logging and events

---

install/0000_30_machine-api-operator_09_deployment.yaml
install/0000_30_machine-api-operator_10_clusteroperator.yaml
pkg/operator/operator.go
pkg/operator/status.go

Every operator shall report a version with name=operator whose value is equal to the RELEASE_VERSION provided by the cluster version operator.
will be enforced via [openshift/origin#22156](https://github.com/openshift/origin/pull/22156)

status: report cluster operator version from payload

---

cmd/nodelink-controller/main.go

I experienced two panics when testing/debugging the nodelink-controller using kubemark. In both cases the panic was because `node.Annotations` was nil.
Additional drive-by fixes to:
- make a logging statement more useful
- to remove a logging statement that was useless

nodelink-controller: ensure node annotations is non nil before adding values

---

owned-manifests/clusterapi-manager-controllers.yaml

Add system-cluster-critical priority class to controller,  without this there is a chance that scheduler evicts these pods when there is a resource crunch.

Add system-critical priority class to controller

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

One additional permission (`ec2:CreateTags`) was added, everything else was just sorted alphabetically.
FYI: https://github.com/openshift/cloud-credential-operator/pull/37
`ec2:CreateTags` is needed since the `ec2: RunInstances` call creates tags for the newly created instances. Before we used the Instance role which had `ec2:*` so this problem didn't show up.

Add additional EC2 permissions to CloudCredential request

---

README.md
pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/conditions/conditions.go
pkg/util/conditions/conditions_test.go
pkg/util/util.go
pkg/util/util_test.go
vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/e2e_test.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go

ConfigMap includes node unhealthy conditions with condition status and timeout. The code will check if the node has the specific unhealthy condition more than condition timeout and if yes will delete the machine object.
ConfigMap has next structure:
```
apiVersion: v1
kind: ConfigMap
metadata:
labels:
noderecovery.kubevirt.io: ""
name: node-unhealth-conditions
namespace: openshift-machine-api
data:
conditions: |
items:
- name: Ready 
timeout: 60s  # support all duration units "ns", "us" (or "µs"), "ms", "s", "m", "h"
status: Unknown
```

Get node unhealthy conditions from the ConfigMap

---

pkg/operator/config.go

This is an incomplete version of #235, but it doesn't use baremetal operator image yet. It doesn't depend on new images (it uses libvirt actuator) so it doesn't need ART blessing for the merge

Don't crash when baremetal provider is used

---

Makefile

Simple way to verify if we are vendoring latest actuator-pkg. This should be executed as a separate optional CI job.
/assign	@enxebre @michaelgugino

verify staleness of vendored cluster-api-actuator-pkg

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

in order to avoid the CVO periodically applying v1beta1 and then having the cloud-cred-operator migrate it to v1 (see https://bugzilla.redhat.com/show_bug.cgi?id=1690069 ), just update the credentialsrequest to v1 (no changes from v1beta1 to v1)

update credentialsrequest from v1beta1 to v1

---

README.md
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This patch introduces support for the managed bare metal platform that
is currently under development under the metalkube github org.
More information about this platform type can be found in
documentation under https://github.com/metalkube/metalkube-docs/.
The actuator and other supporting components are still under active
devleopment, so we just point to an upstream metalkube image for the
actuator for now.  Having this in the machine-api-operator earlier
will make end-to-end testing a bit easier as the platform continues to
be developed.
Signed-off-by: Russell Bryant <rbryant@redhat.com>

Add support for managed bare metal platform.

---

Makefile
hack/verify-actuator-pkg.sh

During adding same check to other repositories it was observed that current implementation is insufficient. This extension tries to update actuator-pkg instead of only runnning `dep check`

extend actuator-pkg staleness check

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go

Kubemark is only for testing against vanilla kubernetes
This *must* not go to ART, and *must* not be referenced in another  operator’s image-references
This stop exposing kubemark image to clusters

Don't expose kubemark image to clusters

---

Makefile
README.md
config/kubemark-config-infra.yaml
config/kubemark-install-config.yaml
install/0000_30_machine-api-operator_08_rbac.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator.go

cluster operators must use the config.openshit.io as source for their top level config.
Rebase and follow up for https://github.com/openshift/machine-api-operator/pull/256

operator: use infrastructure.config.openshfit.io for platformtype

---

pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator.go

Reuse configv1 for handling platforms

Reuse configv1 for handling platforms

---

pkg/operator/config.go

The provider type in the Infrastructure config object is "BareMetal".
This code was expecting "baremetal", which cuased the
machine-api-operator to fall back to the no-op provider instead of
launching the correct clusterapi-manager-controllers pod.

Fix case of BareMetal provider type.

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

Depends on: https://github.com/openshift/cluster-api-provider-aws/pull/182

Drop unused labels

---

install/0000_30_machine-api-operator_08_rbac.yaml

When the machine-api-operator runs the BareMetal machine controller,
it needs access to the BareMetalHost resource.  This patch adds that
necessary access to the ClusterRole.

Add baremetal to the machine-api-manager ClusterRole.

---

README.md
config/machineset.yaml

`install-config.yaml` and `config/status-crd.yaml` were removed by https://github.com/openshift/machine-api-operator/pull/240. Adding the files back and updating links to them.

Fix links to operator status and install config

---

Gopkg.lock
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go

bring https://github.com/openshift/cluster-api-actuator-pkg/pull/61

Re vendor for cluster-api-actuator-pkg 

---

Gopkg.lock
owned-manifests/machine-api-controllers.yaml
pkg/operator/sync.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go

Better naming for controllers deployment

Better naming for controllers deployment

---

pkg/operator/config_test.go
pkg/operator/operator_test.go

The vsphere platform is a no-op for mao, like the none platform.
Adds a unit test to ensure that the mao reports available for no-op platforms.

mao: add support for the vsphere platform

---

config/machine-api-operator-patch.yaml
install/0000_30_machine-api-operator_08_rbac.yaml
install/0000_30_machine-api-operator_09_deployment.yaml
kustomization.yaml
owned-manifests/machine-api-controllers.yaml

FYI: Copying install/0000_30_machine-api-operator_08_rbac.yaml under config/machine-api-operator-patch.yaml and adding
pods.create and pods.delete permissions for kubemark. Since kustomize patch operation replaces entire lists, entire list
of RBAC rules need to be copy pasted into the patch.
Building on top of https://github.com/openshift/machine-api-operator/pull/276

Create dedicated service account for mao

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Before we re-queue the unhealthy node with the condition timeout duration, that can delay
the node remediation, to improve it now we re-queue the unhealthy node with the duration
equals to `conditionTimeout - nodeDurationUnhealthy + second`.

mhc: re-queue after the unhealthy node with the remaining duration

---

pkg/operator/operator_test.go
pkg/operator/sync.go

For listing deployments, ideally deployment lister based on shared informers should have been used because of security aspects. But in the past there was an issue happening and as a stop gap kubeclient was used directly. 
Now that issue is not happening with shared informers and deployLister is being used.

Use deployment client

---

cmd/machine-api-operator/start.go
config/0000_05_config-operator_01_featuregate.crd.yaml
config/machine-api-operator-patch.yaml
install/0000_30_machine-api-operator_08_rbac.yaml
kustomization.yaml
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

Follow up for https://github.com/openshift/machine-api-operator/pull/291 which left machine health check enable by default https://github.com/openshift/machine-api-operator/pull/291/files#diff-554de5523753fda8c93e7008c9bd947fR229

fix feature gate

---

Gopkg.lock
Gopkg.toml
vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/github.com/openshift/api/config/v1/types_scheduling.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go

This commit removes competing dependencies from Gopkg.toml
to allow us to utilize cluster-api-actuator-pkg as the
source of truth for these dependencies.

Simplify Gopkg.toml and update vendor

---

README.md
config/machine-api-operator-patch.yaml
install/0000_30_machine-api-operator_08_rbac.yaml

The MetalKube project had to be renamed.  Reflect the new name here.
Leave the old API group in place for now while we complete the
transition.  We will come back and remove it later.

Reflect MetalKube rename to Metal3.

---

pkg/operator/operator_test.go
pkg/operator/status.go
pkg/operator/sync.go

This commit renames statusFailing to statusDegraded
to conform with other openshift components.

Change operator failing to degraded

---

install/0000_30_machine-api-operator_00_namespace.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

docs/machine-disruption-budget-kpe.md

`MachineDisruptionBudget` design document.
I want to get some first feedback before I will create the PR under the k8s KPE, and it also nice to have documentation together with code, because of it easier to update documentation if it was some code changes.

doc: add machine disruption budget

---

pkg/operator/operator_test.go

So we can test more scenarios. E.g. enabling HC after it was disabled.
@vikaschoudhary16 FYI

Run entire operator in tests instead of just syncClusterAPIController

---

Gopkg.lock
Makefile
vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh

This commit enables running make script directly from
cluster-api-actuator-pkg to reduce drift.

Run make test-e2e from vendor cluster-api-actuator-pkg

---

config/kubemark.yaml
install/0000_30_machine-api-operator_09_deployment.yaml
owned-manifests/machine-api-controllers.yaml

In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …

Fix tolerations

---

cmd/machine-healthcheck/main.go
cmd/nodelink-controller/main.go

Add namespace flag for nodelink controller and machine health check

Namespace flag

---

pkg/operator/featuresgate.go

Machine API created its own feature gate object key and diverged from all other
components expecting 'cluster' key instead. Renaming the key to 'cluster'
to minimize the confusion.

[4.1] Feature gate HC by cluster feature gate object

---

pkg/operator/featuresgate.go

Machine API created its own feature gate object key and diverged from all other
components expecting 'cluster' key instead. Renaming the key to 'cluster'
to minimize the confusion.

Feature gate HC by cluster feature gate object

---

config/machine-api-operator-patch.yaml
install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_10_deployment.yaml
pkg/operator/sync.go

Scope down permissions to openshift-machine-api namespace
Needs - https://github.com/openshift/cluster-api-provider-aws/pull/209
Needs  https://github.com/openshift/machine-api-operator/pull/316

scope down permissions to namespace

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This will be used by the installer to get the creds in the
openshift-machine-api namespace.

Add OpenStack credentials request

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go

As related objects belong to status subresource they were not being udpated as part of the client `Create` request.
This ensures they are included. In a follow up we'll include machines and machineSets
https://bugzilla.redhat.com/show_bug.cgi?id=1717633

Fix related objects to be included in status

---

pkg/controller/disruption/disruption_test.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/testing/testing.go

- move methods from the machine health check tests
- move methods from the machine disruption tests

Move common testing methods to the separate package

---

Gopkg.lock
pkg/operator/operator_test.go
vendor/github.com/openshift/cluster-version-operator/lib/resourcemerge/core.go

This unit test verifies that if hc feature-gate is disabled after enabling it, hc-controller gets removed.

Unit test: Verify hc feature-gate disable after enable scenario

---

Makefile
pkg/operator/config.go
pkg/util/util.go

gosec does static code analysis and checks for common security issues in golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile; it also fixes a couple of warnings that were found (which were probably not very problematic).

Introduce gosec for security checks

---

Gopkg.lock
vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-fmt.sh
vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-lint.sh
vendor/github.com/openshift/cluster-api-actuator-pkg/hack/go-vet.sh
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/common.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/deloyment.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/cluster-autoscaler-operator.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go

Bring https://github.com/openshift/cluster-api-actuator-pkg/pull/70 into mao so the mhc tests can be run through a different make target (out of `make test-e2e`).

Update actuator-pkg dependency

---

pkg/controller/disruption/disruption.go

Standard reflect.DeepEqual sees nil map and empty map as not equal.
PDB uses apiequality.Semantic.DeepEqual which properly accomodates
the case.

Use semantic DeepEqual for map of disrupted machines comparison

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/generated/clientset/versioned/clientset.go
pkg/generated/clientset/versioned/fake/clientset_generated.go

Add `Remediation` field to spec
Defaults to simplest deletion behaviour
Support `remediationReboot` which sets an annotation that consumer remediation systems can react upon
Supersedes https://github.com/openshift/machine-api-operator/pull/346 This allows separation at the right level so consumers can architect their solution by choosing and implementing its strategy, no need for getting infrastructure specifics in the MHC

Remediaton strategies

---

config/machine-api-operator-patch.yaml

Newer version of k8s libraries are referring to
DaemonSets in apps instead of extensions.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations
```
DaemonSet, Deployment, and ReplicaSet resources will
no longer be served from extensions/v1beta1, apps/v1beta1,
or apps/v1beta2 in v1.16. Migrate to the apps/v1 API,
available since v1.9. Existing persisted data can be
retrieved via the apps/v1 API.
```

Add 'apps' apiGroup to daemonsets RBAC

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go
pkg/apis/healthchecking/v1alpha1/machinehealthcheck_types.go
pkg/controller/disruption/disruption.go
pkg/controller/disruption/disruption_test.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/machines/machines.go

This PR integrates `MachineDisruptionBudget` check into the machine health check controller, it makes possible to prevent machine deletion if the cluster has not enough healthy machines.

Integrate machine disruption with machine health check

---

pkg/controller/disruption/disruption.go
pkg/controller/disruption/disruption_test.go

Decrement MD allowed count only when machine has not be previously accounted

---

install/image-references

Get the right reference rendered in the images configmap

Add image reference to GCP machine controllers

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

The cloud credentials operator requires that roles be specified with a
prefix indicating their scope (roles/* for global roles,
roles/project/[project]/* for project-scoped roles, etc)

credentials request: fix gcp roles

---

install/0000_30_machine-api-operator_09_rbac.yaml

This lets the cluster-api-provider-* services read the Infrastructures
object under the `config.openshift.io` API group.
cluster-api-provider-openstack uses it to get the VIP addresses it needs
to configure on the OpenStack ports it creates.

Allow reading Infrastructures from CAP*

---

install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
pkg/apis/healthchecking/v1alpha1/machinedisruptionbudget_types.go

After applying the change and applying:
```yaml
apiVersion: healthchecking.openshift.io/v1alpha1
kind: MachineDisruptionBudget
metadata:
name: mdb-test
namespace: kubemark-provider
spec:
selector:
matchLabels:
machine.openshift.io/cluster-api-cluster: kubemark
sigs.k8s.io/cluster-api-machineset: kubemark-scale-group-2a
maxUnavailable: -2
```
I get:
```sh
The MachineDisruptionBudget "mdb-test" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"healthchecking.openshift.io/v1alpha1", "kind":"MachineDisruptionBudget", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"healthchecking.openshift.io/v1alpha1\",\"kind\":\"MachineDisruptionBudget\",\"metadata\":{\"annotations\":{},\"name\":\ …
```

MDB: Set minimum value constraint for MinAvailable and MaxUnavailable

---

install/0000_30_machine-api-operator_09_rbac.yaml

openshift/kubernetes-drain got updated to list daemonsets as part of `apps` group: https://github.com/openshift/kubernetes-drain/commit/97b0f2710aa6579a688c834e4c2c919adf1912d0#diff-b35cc60e9fab98b13f2a1f43795d4d00
Accordingly cluster-role should be updated. Otherwise we get error like this on Drain():
```
daemonsets.apps "node-ca" is forbidden: User "system:serviceaccount:openshift-machine-api:machine-api-controllers" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-image-registry": node-ca-sc9p8; daemonsets.apps "machine-config-daemon" is forbidden: User "system:serviceaccount:openshift-machine-api:machine-api-controllers" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-machine-config-operator": …
```

Modify machine-api-controller clusterrole for daemonsets

---

install/image-references

Adding images required for a successful Baremetal pod deployment. This is a pre-requisite for https://github.com/openshift/machine-api-operator/pull/302.

Add images required for bringing up a baremetal deployment.

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_12_baremetalhost.crd.yaml
pkg/operator/baremetal_pod.go
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

Changes required for the MAO to also perform the Baremetal deployment.

Integrate baremetal-operator with machine-api-operator

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/testing/testing.go

Watch MachineHealthChecks and enqueue reconcile.Request for the backed nodes.
This is useful to trigger remediation when e.g a machineHealCheck is created against
a node which is already unhealthy and is not able to receive status updates which would otherwise be ignored by MHC
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1704587

Bug 1704587: Reconcile nodes on MHC changes

---

pkg/operator/operator_test.go
pkg/operator/status.go
pkg/operator/status_test.go

This is to be compliant with https://github.com/openshift/cluster-version-operator/blob/b57ee63baf65f7cb6e95a8b2b304d88629cfe3c0/docs/dev/clusteroperator.md#what-should-an-operator-report-with-clusteroperator-custom-resource
When known hazardous states for upgrades are determined, specific "Upgradeable=False" status can be added with messages for how admins can resolve it.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1727021

Bug 1727021: Set Upgradeable condition on ClusterOperator status

---

Gopkg.lock
Gopkg.toml
install/0000_30_machine-api-operator_02_machine.crd.yaml
vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go

Given we already support AWS, Azure and GCP instalations of OpenShift,
reading values from machine provider config is no longer an option.
Instead, let's read all needed values from machine annotations and labels.
Each actuator will be then responsible for making sure every machine
has all the annotations and labels that are needed to properly display
additional machine columns set.

Get values for CRD's additionalPrinterColumns from annotations and labels instead of machine provider config

---

pkg/operator/baremetal_pod.go

The "metal3-controller" service account does not exist.  Instead, use
the "machine-api-controllers" service account.

baremetal: Fix service account name.

---

install/0000_30_machine-api-operator_13_baremetalhost.crd.yaml

The BareMetalHost CRD being installed is a skeleton version, without
the OpenAPI validation and other settings of the more complete
CRD. Update the file based on the most recently generated version from
openshift/baremetal-operator repository.

update BareMetalHost CRD

---

pkg/operator/baremetal_pod.go

static ip container fails to come up, as it can not see host network
interfaces:
```
[root@host dev-scripts]# oc logs -n openshift-machine-api pod/metal3-7557d6d788-cfdt6  --container=metal3-static-ip-set
+ '[' -z ens3 ']'
+ '[' -z 172.22.0.3/24 ']'
+ /usr/sbin/ip address flush dev ens3
Device "ens3" does not exist.
```

baremetal: set host networking to true

---

pkg/operator/baremetal_pod.go

The path to this command was wrong.  The binary is under /, not /bin.
https://github.com/openshift/ironic-static-ip-manager/blob/master/Dockerfile.ocp

baremetal: Fix path to refresh-static-ip.

---

pkg/operator/baremetal_pod.go

This component is not being used in this version of OpenShift, so drop
it.

baremetal: Drop ironic-exporter.

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

After cloud credential operator starts supporting resource group
scoped credential minting for Azure, all CCO will be required to set
at least one role in role bindings. If a CCO failed to do so,
no secret with azure credential will be minted.
Contributor role permissions should be sufficient. If not, please extend the list of role bindings with additional roles.
PR adding the support for resource group scoped credentials: https://github.com/openshift/cloud-credential-operator/pull/95

Set default role for minted credentials to Contributor

---

install/0000_30_machine-api-operator_09_rbac.yaml

When using the baremetal infrastructure platform, the
baremetal-operator component within the metal3 deployment needs to be
able to set the owner reference on Secrets.
Secrets are used to hold credentials used to talk to the out-of-band
management controllers (BMCs) on bare metal servers.  These Secrets
are associated with a BareMetalHost resource.  The BareMetalHost
controller will set the owner on the Secret.

rbac: Allow update and patch of secrets.

---

install/0000_30_machine-api-operator_09_rbac.yaml

When utilising the baremetal infrastructure platform the baremetal
operator component needs to be able to update additional resources
for baremetal hosts, namely the status and the finalizer. This patch
ensures that it can do so, and will now allow hosts to be registered
with OpenShift as `BareMetalHosts` and as a result inside of Ironic.

RBAC: Add additional metal3.io resource access

---

install/0000_30_machine-api-operator_09_rbac.yaml

A follow-on change to openshift/machine-api-operator#384 and openshift/machine-api-operator#385, allowing baremetal-operator set an owner reference on the BMC secrets.
The main change needed is delete permissions on the secret are required to avoid:
> cannot set an ownerRef on a resource you can't delete
As in openshift/machine-api-operator#385 update permissions on baremetalhost finalizers are required to avoid:
> cannot set blockOwnerDeletion if an ownerReference refers to a
> resource you can't set finalizers on
and update permissions on baremetalhost status is required to avoid:
> cannot update resource "baremetalhosts/status"
Limit permissions on these latter two subresources to just update instead of the more broad permissions in openshift/machine-api-operator#385.
Finally, delete …

rbac: allow delete of secrets and baremetalhosts

---

pkg/controller/nodelink/nodelink_controller.go
pkg/controller/nodelink/nodelink_controller_test.go

If an error occurs looking up the machine we went on to log the
machine name using `machine.GetName()` as part of the error message.
That triggered a nil pointer dereference given that machine is nil
when lookup fails.
Add explicit unit test so that we don't regress.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747246

bug 1747246: nodelink_controller: fix SEGV in findNodeFromMachine()

---

install/0000_90_machine-api-operator_04_alertrules.yaml

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1744752

Bug 1744752: Add a new alert rule for reporting the Machine-api Operator failure

---

install/0000_30_machine-api-operator_08_rbac.yaml

cherry-picking https://github.com/openshift/machine-api-operator/pull/366
This change is required to fix CI on the PR, https://github.com/openshift/cluster-api-provider-aws/pull/253
```
daemonsets.apps "node-ca" is forbidden: User "system:serviceaccount:openshift-machine-api:machine-api-operator" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-image-registry": node-ca-brnl4; daemonsets.apps "machine-config-daemon" is forbidden: User "system:serviceaccount:openshift-machine-api:machine-api-operator" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-machine-config-operator": 
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-aws/253/pull-ci-openshift-cluster-api-provider-aws-release-4. …

cherry-picking #366: Bug 1732929: Modify machine-api-controller clusterrole for daemonsets

---

cmd/machine-api-operator/start.go
config/machine-api-operator-deployment.yaml
install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
install/0000_30_machine-api-operator_10_service.yaml
install/0000_90_machine-api-operator_03_servicemonitor.yaml
install/image-references
kustomization.yaml

This PR is adding changes to expose metrics endpoint on https and also changes at other objects for integration with openshift-monitoring at https.
This PR is also restricting http port access only on loopback ip.
[kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy/tree/master/examples/rewrites#rewriting-subjectaccessreviews-example) container is being run alongside operator container which runs metrics server in the same pod. kube-rbac -proxy validates authz and authn on behalf of the metrics server and if success, proxies the incoming https request to the metrics server(which is listening on 127.0.0.1 and http port 8080).
It uses `TokenReviews()` and `SubjectAccessReviews()` apis internally for validation of token authentication and authorization respectively. These apis are …

Expose metric endpoint on https

---

cmd/machine-healthcheck/main.go
cmd/nodelink-controller/main.go

Disable metrics to avoid pod collisions. This was enabled by default it https://github.com/kubernetes-sigs/controller-runtime/pull/510/files
See https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-aws/261/pull-ci-openshift-cluster-api-provider-aws-master-e2e-aws-operator/727/artifacts/e2e-aws-operator/pods/openshift-machine-api_machine-api-controllers-6dd895f447-zglqq_nodelink-controller.log

Disable metrics to avoid pod collisions

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/sync.go

Several containers with the Metal3 deployment need to have access to the mariadb_password. Generate a random password within the MAO and make it available within the openshift-machine-api namespace only if it doesn't already exist.
Mariadb-password is currently being created by the installer at : https://github.com/openshift-metal3/dev-scripts/blob/master/utils.sh#L193. Once the capability to generate the maridb password from within the MAO has been added, it will be removed from the installer.

Create maraidb_password within the MAO for use by the baremetal IPI deployment

---

pkg/operator/baremetal_pod.go

openshift-tests says "Always" is a invalid container image pull policy.
Fixes: #407

Switch imagePullPolicy in baremetal pod to IfNotPresent

---

pkg/operator/sync.go

Because otherwise stuck deployments will result in the not-very-useful `timed out waiting for the condition` errors [like][1]:
```
Oct 17 18:41:52.205 E clusteroperator/machine-api changed Degraded to True: SyncingFailed: Failed when progressing towards operator: 4.3.0-0.ci-2019-10-17-173803 because timed out waiting for the condition
```
Also use `%s` instead of `%q` for formatting the deployment name, because we control the names being monitored and they don't contain whitespace or other potentially-confusing characters.
[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/8809

Bug 1763293: pkg/operator/sync: Track lastError in waitForDeploymentRollout

---

install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml

A couple of fields in the BaremetalHost CRD are being marked as
optional as part of https://github.com/metal3-io/baremetal-operator/pull/322.
Keeping the BaremetalHost CRD in the MAO current with those changes.

Marking a couple of fields in the BaremetalHost CRD optional

---

cmd/machine-api-operator/start.go
install/0000_30_machine-api-operator_11_deployment.yaml

MAO is going through reconciles about every three minutes consistently. This is because the mao deployment receives update events which I can only think are coming from the CVO.
e.g
- https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/417/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1411/artifacts/e2e-aws-operator/pods/openshift-machine-api_machine-api-operator-6b74c4f5d6-zcd26_machine-api-operator.log
- https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/422/pull-ci-openshift-machine-api-operator-master-e2e-aws/1534/artifacts/e2e-aws/pods/openshift-machine-api_machine-api-operator-7bf945646d-vc2pk_machine-api-operator.log
When CVO calls ensureDeployment it might wrongly return `modified=true` …

reduce reconciling events

---

pkg/operator/baremetal_pod.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

Only reconcile owned deployments for update/delete events.
This would prevent other deployments in the `openshift-machine-api` e.g autoscaler, mao deployment (owned by cvo) to trigger the reconciliation loop here.
Opted by annotation rather than ownerRefs pointing to mao deployment as this would increase complexity and skew to contemplate reconciliation when the mao is running remotely

Only reconcile owned deployments

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

This allows to find a backing machine for a node not found, therefore letting remediation to take place when reconciliation is triggered by a node deletion.

bug 1765427: Add index for getting machines from node.

---

install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_10_service.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
install/0000_30_machine-api-operator_12_clusteroperator.yaml
install/0000_90_machine-api-operator_03_servicemonitor.yaml
install/0000_90_machine-api-operator_04_alertrules.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

Enforce Requeue when machine is not provisioned yet
Enforce Requeue when machine has no node yet
Enforce Requeue right after creating an instance
Prepend machine name to logging consistently

Machine controller fixes

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

The new image name is ironic-machine-os-downloader.
Fixes : https://github.com/openshift/machine-api-operator/issues/451

bug 1783973: Update the image name for ironic-rhcos-downloader

---

pkg/apis/vsphereprovider/v1alpha1/vsphereproviderstatus_types.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go

Reconcile based on task status.
Support networking devices and set IPs on status.
```
I1220 10:35:09.907747   27157 reconciler.go:123] test: does not exist
I1220 10:35:09.907828   27157 controller.go:386] test: going into phase "Provisioning"
I1220 10:35:10.067193   27157 controller.go:295] test: reconciling machine triggers idempotent create
I1220 10:35:10.067239   27157 actuator.go:56] test: actuator creating machine
I1220 10:35:11.229458   27157 reconciler.go:63] test: cloning
I1220 10:35:11.229524   27157 session.go:101] Find template by instance uuid Workloads/Cuppett Fedora
I1220 10:35:11.533673   27157 session.go:111] Find template by name Workloads/Cuppett Fedora
I1220 10:35:22.403051   27157 reconciler.go:264] Getting network devices
I1220 10:35:22.403191   27157 …
```

Add task reconciling and networking

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go

This adds three printer columns (`MaxUnhealthy`, `ExpectedMachines`, `CurrentHealthy`) to the `MachineHealthCheck` CRD.
The description of each I've come up with from my understanding of MHCs, these will need confirming. Not sure if there is a pattern to be followed for that
I have not tested this on a cluster yet, will do so before marking ready

[OCPCLOUD-700] Add customer printer columns for MachineHealthCheck CRDs

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

This adds support for fetching the user-data secret referenced in the
ProviderSpec of a Machine using the vsphere provider, and passing that
data as ignition config via guestinfo variables.

vsphere: Add support for passing ignition user-data

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Introduce support to set the providerID on the machine spec based on the biosUUID consistently with https://github.com/kubernetes/cloud-provider-vsphere/
/hold

vsphere: set providerID

---

install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml

A new CRD is being added to metal3.io API group that contains config
necessary to provision baremetal hosts.

Adding a new CRD for configuration needed for Baremetal provisioning

---

hack/update-codegen.sh
hack/verify-codegen.sh
pkg/apis/vsphereprovider/v1alpha1/register.go

This fixes a few small things so that `make generate` works for the types in the vsphere provider code.

Fixes to codegen for vsphere provider

---

cmd/machine-api-operator/client_builder.go
cmd/machine-api-operator/start.go
install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/operator.go

This is so baremetal can fetch the `provisioning.metal3.io` object and parameterize their deployment. Related openshift/api#540 and #460

Expose a dynamic client in the Operator struct

---

pkg/operator/baremetal_config.go
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/sync.go

Provide configuration values read from Baremetal Provisioning CR to
Metal3 containers via env vars. When the CR is not available, fall
back to reading the config map for configuration values.

Pass config values read from Baremetal Provisioning CR to Metal3

---

Dockerfile
Dockerfile.rhel7
Makefile
install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator_test.go

Add support for mao to run the vsphere machine controller.
The machineset controller development was moved into this repo by #441 and the vsphere actuator lives in this repo, therefore the binaries live in the mao image unlike other providers with their own image e.g aws

Vsphere provider

---

install/0000_30_machine-api-operator_00_credentials-request.yaml
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler_test.go

Creates a credentials request to retrieve VSphere creds. Update provider to expect credentials in required format: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/k8s-secret.html

VSphere: Provider Credentials

---

install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
pkg/operator/baremetal_config.go
pkg/operator/baremetal_test.go

Augment the provisioning CRD to also contain a URL where the metal3 cluster can download a RHCOS image. Read Rhcos Image URL from this CR and pass it to metal3 cluster.

Bug 1796189: Add support for image download url in the provisioning CRD

---

install/0000_30_machine-api-operator_02_machine.crd.yaml
pkg/apis/machine/v1beta1/machine_types.go

this change makes the comments for the MachineState.Phase match the
actual phases used in the code. it also updates the generated file that
goes with it.

Bug 1797688: update description for MachineState phases

---

pkg/controller/machine/controller.go

Add log message when draining the unreachable node.

Bug 1733474: Add log message when draining the unreachable node

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Discussing with the metal3 folks, we’d like to watch the machine for the annotation instead if the node. This avoids the creation of a controller that just relays the annotation from the node to the machine.

Bug 1800423: Apply the reboot annotation to the machine

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

From BZ description:
Deleting the Node object in Kubernetes signals to the cluster that no pod on that node is running and that it is safe to release any storage or process locks that ensure two processes can't be running on different nodes with the same name or volumes.  The machine controller was deleting the node before the machine was fully terminated, which means that a stateful set controller would be able to launch two pods with the same name running on the cluster at the same time, which violates our cluster safety guarantees.
Fix is to wait for machine is confirmed shut down by cloud provider before deleting the Node object.

Bug 1800314: Check if instance exists before proceeding with deletion

---

pkg/operator/baremetal_config.go
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go

CACHEURL is no longer needed as env vars for containers
that are part of the metal3 cluster.

Bug 1797799: Remove CACHEURL as a config for metal3

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Since MHC has no control over how the machine is remediated, it would be
better not to imply that it will (only) be via reboot.

Bug 1800425: More appropriate annotation name

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
install/image-references

these placeholders will get replaced by the release-creation tooling[0].
this change is inspired by a previous commit[1] to the
machine-config-operator.
[0]: https://github.com/openshift/cluster-version-operator/blob/33079c7732b99394f78c4fecb8d7d277c87ef02c/docs/dev/operators.md#how-do-i-ensure-the-right-images-get-used-by-my-manifests
[1]: https://github.com/openshift/machine-config-operator/pull/750

Bug 1802179: use generic image placeholders for install

---

Dockerfile
Dockerfile.rhel7
Makefile
install/0000_30_machine-api-operator_01_images.configmap.yaml
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator_test.go

Reverts openshift/machine-api-operator#474
vSphere IPI was dropped from 4.4, therefore we don't want the controller to run in this release. We'll enable it back once master opens for 4.5

Bug 1803736: Revert "Vsphere provider"

---

install/0000_30_machine-api-operator_00_namespace.yaml

mao should follow normal admission control rules for a cluster.

BUG 1806438: Drop run-level

---

pkg/controller/machine/controller.go

Fix `skipWaitForDeleteTimeoutSeconds` format in log message

Bug 1804635: Fix timeout formatting

---

README.md

This should point to the OpenShift fork of CAPO instead of the upstream
repo from kubernetes-sigs.

Update URL for CAPO repository

---

hack/gen-crd.sh
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml

In a ROKS cluster, the console UI should not show machine related views since
machine management is done outside the cluster. The UI will remove the
views as long as the CRDs are not present.

Bug 1809333: ROKS - remove machine related CRDs from cluster

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

This allows users to set the previously hard coded `timeoutForMachineToHaveNode` value in the machine health checking algorithm as part of the `MachineHealthCheckSpec`.
If the value is not set, we default to the original hard coded 10 minute timeout.
Ideally the field would be a `metav1.Duration` but I've put it as a string because of the same reasons as the `UnhealthyCondition.Timeout` field.
/cherry-pick release-4.4
/cc @enxebre

[OCPCLOUD-774] Add Node startup timeout API field

---

install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

Without the runlabel https://github.com/openshift/machine-api-operator/pull/496, we’ll run as a high user by default, no need to say run me as non root.
Otherwise when removing the runlevel completely for the `openshift-machine-api` namespace https://github.com/openshift/cluster-autoscaler-operator/pull/133 the kube controller manager complains with ```Error creating: pods "machine-api-operator-75c887884f-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 65534: must be in the ranges: [1000340000, 1000349999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 65534: must be in the ranges: [1000340000, 1000349999]]``` …

BUG 1806438: Remove explicit securityContext and add granular securitycontextconstraints "use" permissions in machine-api-controllers clusterRole

---

pkg/operator/operator_test.go
pkg/operator/status.go
pkg/operator/status_test.go

This changes the behavior of the `statusProgressing` and `statusDegraded` methods to not modify other unrelated status conditions.  The previous behavior was causing the ClusterOperator status to oscillate between Degraded and Progressing when there was a problem syncing the deployments, because each transition was overwriting the other.
This also changes the initial creation of the ClusterOperator resource to set default status conditions.

Don't oscillate between Degraded and Progressing status

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Add unit tests for vsphere reconciler. I will open a followup PR with new test cases later.

Add unit tests for vsphere reconciler

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

"roles/compute.networkAdmin" https://cloud.google.com/compute/docs/access/iam includes "compute.targetPools.*". This is currently used to add masters to LB in DR scenarios.
https://bugzilla.redhat.com/show_bug.cgi?id=1807125
/cherrypick release-4.4
/cherrypick release-4.3
/cherrypick release-4.2

BUG 1807125: Add GCP roles/compute.loadBalancerAdmin role

---

cmd/machine-healthcheck/main.go
pkg/controller/machine/controller.go
pkg/controller/machine/machine_controller_suite_test.go
pkg/controller/machine/machine_controller_test.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machineset/machineset_controller_suite_test.go
pkg/controller/machineset/machineset_controller_test.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/operator/operator_test.go
pkg/operator/status_test.go

This PR:
1. Removes unused code
2. Replaces unreasonable structures
3. Removes duplicate imports
4. Fixes `t.Fatalf` call from separate go routine

Remove unusued code and cleanup

---

pkg/controller/machine/controller.go

This will be used by AWS/GCP/Azure actuators to label Machines as either On-Demand or Spot depending on the provider and the appropriate terminology.
This will allow selectors for Machine's based on this label

Add Interruptible Instance label name

---

pkg/controller/machine/controller.go

Spelling never was my strong point! Should be an `i` not an `a`
```
- MachineInterruptableInstanceLabelName
+ MachineInterruptibleInstanceLabelName
```

Fix typo in interruptible instance label

---

install/0000_30_machine-api-operator_01_images.configmap.yaml

Fix vSphere image link, it should point to `registry.svc.ci.openshift.org`

BUG 1812800: Fix vSphere image link

---

README.md

the ci section contains a link to the master configuration for the
machine api operator component registry, this change fixes the link to
the current location.

fix the master ci config link in readme

---

README.md

in the dev section there are instructions for running on vanilla
kubernetes, this change fixes the broken link for the deployment
manifest step.

update deployment link on readme

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

This PR ensures that if a user specifies `{"maxUnhealthy": 1}` or `{"maxUnhealthy": "1"}`, the behaviour is consistent between the two.
Previously setting `{"maxUnhealthy": "1"}` was equivalent to setting `{"maxUnhealthy": "1%"}` which may have been surprising behaviour to users

Bug 1812862: Allow Int in String within MHC MaxUnhealthy

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

The CSR that is created uses the name of the virtual machine.
There are no other SAN(s) within the CSR for the cluster-machine-approver
to use.
Adding an item to status addresses to include InternalDNS with
VM name.

vSphere: Add InternalDNS with virtual machine name to Status addresses

---

hack/gen-crd.sh
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml

In a ROKS cluster, the console UI should not show machine related views since
machine management is done outside the cluster. The UI will remove the
views as long as the CRDs are not present.

Bug 1811161: ROKS - remove machine related CRDs from cluster [4.4]

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

This allows MachineHealthChecks to be created with an empty selector (`selector: {}`) which will match all machines.
This currently works, but the watch maps for watching Nodes and Machines currently assume no Nodes or Machines should match when the selector is empty, this change ensures all Nodes/Machines match when the selector is empty as per the behaviour of an empty selector normally

Bug 1815680: Allow MachineHealthCheck to have an empty selector

---

hack/gen-crd.sh
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml

In a ROKS cluster, the console UI should not show machine related views since
machine management is done outside the cluster. The UI will remove the
views as long as the CRDs are not present.

Bug 1814092: ROKS: remove machine related CRDs from cluster [4.3]

---

cmd/machine-api-operator/start.go
install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/baremetal_test.go
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

This PR enables the Machine API Operator to run the Termination Handler added to the AWS cloud provider in https://github.com/openshift/cluster-api-provider-aws/pull/308 by running a DaemonSet on nodes labelled as interruptible
Need to test on a real cluster before this merges
/hold

[OCPCLOUD-803] Run Spot Termination Handler from Machine API Operator

---

pkg/controller/vsphere/reconciler.go

To support setting the hostname of the RHCOS guest
add a extra config key/value `guestinfo.hostname`.

vsphere ipi: add extra config key with guestinfo hostname

---

pkg/operator/operator.go
pkg/operator/sync.go

In commit 69986ee5, we moved from using the CVO variant of the resourceapply library to the openshift/library-go variant. The CVO variant, a deep comparison is performed of the expected state with the current state to decide whether to apply an update. In the library-go variant, this decision is based on an objectMeta comparison, particularly whether the current generation of the resource matches the "expected generation".
Currently we use the resources reported observedGeneration as this "expected generation" input. This doesn't make sense, since this will only differ from the current generation when the deployment controller hasn't yet reconciled an update. You can see this issue by scaling down the machine-api-controllers deployment and observing that MAO happily leaves it that way. …

Properly apply updates to MAO-managed workloads

---

cmd/machine-api-operator/client_builder.go

Currently we do this:
```
./bin/machine-api-operator start --images-json ./images.json --alsologtostderr --v=3
I0328 16:34:18.688008   36609 start.go:58] Version: 0.1.0-780-g4e3ac1e2-dirty
F0328 16:34:18.688396   36609 start.go:66] error creating clients: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```
Make us a bit friendlier:
```
./bin/machine-api-operator start --images-json ./images.json --alsologtostderr --v=3
I0328 16:35:50.846740   10863 start.go:58] Version: 0.1.0-780-g4e3ac1e2-dirty
F0328 16:35:50.846808   10863 start.go:66] error creating clients: Not running in-cluster? Try using --kubeconfig
```

Give friendly hint when not starting in-cluster

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/testing/testing.go

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1816398
We want to relax the hard dependency on machineSets and let remediation to happen for machines that are owned by any controller.
This will enable a possible integration for a self healing control plane.

bug 1816398: Let MHC to remediate any machine owned by a controller

---

pkg/apis/vsphereprovider/v1alpha1/vsphereproviderconfig_types.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Add support for passing disk devices to vsphere machines. The code is based on upstream one https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/pkg/services/govmomi/vcenter/clone.go#L74-L85

Add support for passing disk devices to vsphere machines

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

After testing with latest MAO I noticed that InternalDNS was an empty string.
I have tested this and the `ObjectName()` method functions as expected.  
The Name method returns an empty string instead of the VirtualMachine
name.  ObjectName uses VirtualMachine propertie `name` to return
the name.
Update tests

vsphere ipi: replace .Name() with .ObjectName()

---

Dockerfile
Dockerfile.rhel7
go.mod
pkg/operator/baremetal_test.go
pkg/operator/config.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

This changes the image for the MachineSet controller deployed in the `machine-api-controllers` deployment to use the `machine-api-operator` image instead of the `provider` image.
Also adds tests to check the output of `maoConfigFromInfrastructure` as this was not previously tested

[OCPCLOUD-815] Use MachineSet controller from MAO image

---

install/0000_90_machine-api-operator_04_alertrules.yaml

This is to make it more obvious that the phases is not even set for the edge case where this might happen if a machine controller was never run.

Bug 1810443: Rephrase MachineWithNoRunningPhase message

---

install/0000_30_machine-api-operator_09_rbac.yaml

This allows the machine-api-temrmination-handler service account to use hostnetwork, fixing the DaemonSet that was unable to deploy due to SCC constraints

BUG 1823308: Allow machine-api-termination-handler to use hostnetwork SCC

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

A [new case](https://github.com/kubernetes/kubernetes/pull/89482#issuecomment-604102034) of malformed IntOrPercent was brought to my attention, I have added a test case and fixed the behaviour of our implementation

BUG 1825851: Ensure malformed IntOrPercent returns error

---

pkg/operator/operator_test.go
pkg/operator/sync.go
pkg/operator/sync_test.go
pkg/util/conditions/conditions.go

There might be scenarios where the operator flips between degraded false/true. 
E.g the managed deployment rolls out successfully. A particular business logic path makes one container to panic consistently. Go to 1.
https://github.com/openshift/api/blob/2ea89d203c53704f1fcfeb55c13ededab14fd020/config/v1/types_cluster_operator.go#L168
This results in a lower quality of service and Degraded should not oscillate but rather should remain true until the persistent observation of the problematic condition is fixed.
This PR cover this scenario by raising the expectation for the managed deployments to be available for a minimum duration, i.e 3 min.

Bug 1824943: check minimum available time in waitForDeploymentRollout

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This relies on https://github.com/openshift/cloud-credential-operator/pull/181 merging first, but I have manually tested the IAM credentials will allow using Customer Manager Keys for encrypting EBS volumes

BUG 1815219: Allow machines to have encrypted EBS volumes with non-default key

---

go.mod
pkg/controller/machineset/controller.go
pkg/controller/machineset/delete_policy.go
pkg/controller/machineset/status.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/util.go

Replace all `errors.Wrap(f)` with `fmt.Errorf` to drop the dependency on `github.com/pkg/errors`.
This ensures that the vSphere provider is compatible with the changes introduced in #559

BUG 1826017: Switch to Go errors instead of github.com/pkg/errors

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go

This PR should fix the case when VM misses UUID and `Exists()` call fails to find VM. Failing to find VM causes the controller to try to create an existing VM, which leads to endless loop of failing tasks.
The proposed fix is to fallback to searching by name when UUID search fails.

Bug 1822665: Find vm by name if UUID search fails

---

install/0000_90_machine-api-operator_04_alertrules.yaml

There seems to be a race between mao and prometheus to be able to provide a valid bearer token. It seems to take up to 5 min based on the logs:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/162/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws/722/artifacts/e2e-aws/pods/openshift-machine-api_machine-api-operator-649f77c85d-k4nxj_kube-rbac-proxy.log
This relax the availability alerts.

Bug 1804464: Relax timeout for metrics availability alerts

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go

It's better to return an error on empty task reference. Returning `nil` without any error means we need to check the returned task for `nil` every time and it also brings a bit of confusion to code.

Bug 1827601: vSphere - Return error on empty task reference

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Attaching a tag to VM takes about 20-30 seconds and waiting for it becomes a bit annoying. We should check if the tag was already attached to VM and skip attaching it for multiple times.

Bug 1827593: Check if tag is already attached to vm

---

pkg/controller/vsphere/reconciler.go

We should support the ability to switch off VM but current implementation turns on VM in every machine update. 
I removed the reconciliation of power state and set `PowerOn:  true` on machine creation. We have this part copied from upstream and powerOn set to true shouldn't be an issue for us.

Bug 1829333: vSphere - Don't reconcile power state

---

pkg/operator/baremetal_config.go

Allow an empty string to be passed in as DHCP range when the DHCP
server is external in a Baremetal IPI installation.

Bug 1826983: Fix External DHCP range values for Baremetal configuration

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

Setting machine instance state to unknown on machine failure

Bug 1808971: Machine status shows "running" when an instance was terminated

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

If an AWS account has not had a spot instance run in it before, then a service-linked-role required for spot instances will not exist. Typically this would be created upon the first spot request being created, but it requires the user to have permission to create service linked roles.
This should resolve errors like:
```
Error launching instance: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.
```
Ideally this service linked role would be independently but I don't think there's anything within Openshift that can create a service linked role as a one off apart from the installer, but that wouldn't help upgrades
Ref: https://confluence.atlassian.com/bamkb/bamboo-fails-to-lodge-spot-in …

BUG 1831577: Allow Machine API to create Service Linked Role for Spot instances

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Reconcile machine power state annotation

Bug 1829408: Reconcile machine power state annotation

---

pkg/controller/vsphere/reconciler.go

Our current implementation allows users to either specify `resourcePool` in provider spec or leave it empty and fallback to default one. In case when more than one resource pools found lookup fails and the machine is stuck in `Provisioning` phase. In order to avoid machine getting stuck, this PR introduces machine failure on lookup error. 
I have issues with creating additional resource pools in the mocked environment so tests will come later.

Bug 1833256: [vSphere] Fail machine if multiple resource pools found

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

A follow-up for https://github.com/openshift/machine-api-operator/pull/585
PR adds similar logic for datastores and folder + unit test coverage increase

Bug 1838504: [vSphere] Fail machine on invalid provider spec values

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go
pkg/controller/vsphere/util_test.go

This PR adds the ability to read port from provider config. We should be able to append port to the server's address.
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/k8s-secret.html#create-a-k8s-secret.
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html

Bug 1839694: [vSphere] Add ability to read port from provider config

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go
pkg/controller/machine/machine_controller_suite_test.go
pkg/controller/machine/machine_controller_test.go

By calling `Patch`, the client overwrites the `machine` with the state on the API server. This meant that all changes to subresources before the patch (eg Status fields) get wiped out.
Therefore, the call to `Status.Patch` had no effect as the status had been reset.
I've rewritten the tests to use testenv as the fakeclient doesn't exhibit this behaviour, so the tests weren't catching this problem

Bug 1840552: Ensure status patch is after annotation patch when setting phase

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go
pkg/controller/vsphere/util.go
pkg/controller/vsphere/util_test.go

We should get the insecure flag from provider config and default to secure connection if flag is missing
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#single-vcenter

Bug 1840665: [vSphere] Get insecure flag from provider config

---

pkg/operator/status.go
pkg/operator/status_test.go

We've used `ReasonEmpty` since 4000ff88f0 (#174).  But if we feel like we have a message we want to set to help humans understand the condition, we should be setting a reason string for machines too.  `AsExpected` follows [the library-go precedent][1].
Also use `AsExpected` for some message-less but expected conditions, like `Progressing=False` and `Degraded=False`.  Having a reason makes it easier for folks skimming logs to see that the condition is in its happy state, and doesn't cost us any effort to set.
Also shuffle `defaultStatusConditions` a bit:
* `Progressing=False` didn't make sense to me as an initial condition.  It is now:
Progressing=True Initializing: Operator is initializing
to show that the operator is working on getting itself ready.
* `Available=False` is a surprising …

pkg/operator/status: Change ReasonEmpty to ReasonAsExpected

---

cmd/vsphere/main.go

Reduce sync period to 10 minutes because the default value is 10 hours and it makes cloud provider changes ignored by the controller. 
We have similar sync time in other controllers.

[vSphere] Reduce sync period to 10 minutes

---

README.md

this change helps to make the FAQ more discoverable.
although the FAQ document is in the root of the repository, i think it would be helpful to put a link front-and-center for people who navigate to this project repo.

add a link to the FAQ in the README

---

pkg/apis/machine/v1beta1/machine_webhook.go

The need for this label is mainly for AWS to be able use it to filter instances by name and clusterID when there's no an instanceID available yet https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/reconciler.go#L358-L371
This is just a detail we as devs choose to implement this way, it's not a legitimately user input API field. The clusterID is by design implicit and available on the context and client that the machine is being created at any time. Therefore I don't think this should be exposed as user input at all or defaulted by a webhook at creation/updating time. The controller should be able to discover and pass the clusterID through with or without a webhook at the front. We could even eventually drop the label and use a different mechanism to …

Drop clusterID defaulting label

---

pkg/apis/machine/v1beta1/machine_types.go
pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go
pkg/controller/machine/machine_controller_suite_test.go
pkg/controller/machine/machine_controller_test.go

Set clusterID label on the machine using controller. Currently, we require the user to set clusterID label manually, this PR introduces usage of infrastructure resource for setting label.

Set clusterID label on machine

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

We would like to have external remediation for Machine without controller owner, to allow masters remediation.
Signed-off-by: Nir <niry@redhat.com>

Allow external remediation even if there's no controller owner

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

The namespace of the UserDataSecret Namespace was mistakenly required when Azure defaulting and validation was implemented.
In existing clusters, the UserDataSecret Namespace has been allowed to be emptied and has been inferred in the controller rather than requiring it to be set.
This PR fixes the logic to allow the field to be empty and restores the previous behaviour

Allow the Azure UserDataSecret Namespace to be omitted

---

pkg/controller/vsphere/reconciler.go

Add check for nil `MoTask` in order to avoid actuator's panic.

[vSphere] Add check for nil motask

---

OWNERS

There is apparently tooling that uses this, came up in chat.
See e.g. the MCO:
https://github.com/openshift/machine-config-operator/blob/master/OWNERS#L12

OWNERS: Add a component link for BZ

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/vsphere/main.go
pkg/operator/sync.go

OCPCLOUD-785 - health checks for all machine API controllers
This introduce support for readinessProbe and livenessProbe [1] for the owned machine controllers deployment and its machineSet, MHC and machine controller containers.
This will let the kubelet to better acknowledge about these containers lifecycle and therefore letting us to be more robust to signal the operator degradability on the clusterOperator status.
This PR needs [2], [3] and [4] to work and pass CI so the probes included in the container spec here can get a 200 from the machine controllers. Also additionally [5], [6] and [7] must the same to not break or the probes included in the container spec here  will fail will and result in the containers getting restarted.
This also reverts accidental rebase and put back the …

Add liveness/readiness probes

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

Adds a defaulting and validating function for vSphere provider specs and registers it with the existing webhooks introduced in #601

[OCPCLOUD-883] Add defaulting and validation via Webhook for vSphere 

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

If the Machine has already been deleted, we do not need to delete it again. Nor do we need to send an event to say that we have deleted it a second (or third...) time.
This PR fetches the Machine as we attempt to remediate and checks if the Machine has already been deleted before attempting to delete the Machine and sending the event.

Bug 1844986: Do not send Machine deletion event if the Machine has already been deleted

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Return invalid machine configuration error on missing VM template and missing user data secret

Bug 1843327: [vSphere] Improve provider spec validation

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

When creating the webhook E2E tests I managed to create a MachineSet for AWS which just had the AMI ID set, other fields were defaulted as expected, but the region was not. Without a region set, the actuator fails to create a machine and as such, we should require that the region be set on the providerSpec when objects are created or updated.
```
E0702 10:52:02.388989       1 reconciler.go:200] ci-op-74pcs6y0-79b09-gdhds-webhook-2zmct: error getting existing instances: MissingRegion: could not find region configuration
E0702 10:52:02.389017       1 controller.go:280] ci-op-74pcs6y0-79b09-gdhds-webhook-2zmct: failed to check if machine exists: MissingRegion: could not find region configuration
E0702 10:52:02.389067       1 controller.go:258] controller-runtime/controller "msg"="Reconciler …
```

Require region to be set on AWS ProviderSpec

---

docs/dev/metrics.md

This change adds a paragraph and example at the beginning of the metrics
doc describing how to performa a manual scrape on the prometheus port.
This is being added to help developers understand how to interact with
metrics directly.

add a section to metrics doc on how to scrape

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go
cmd/vsphere/main.go
pkg/operator/sync.go

Added leader election support for all outstanding controllers in MAO .
Using leader election will add stronger guarantees than we have today that only one controller is running at a time to protect against edge cases where the deployment replica could be increased or upgrades with permissive maxSurge.
Relevant provider PRs:
- https://github.com/openshift/cluster-api-provider-gcp/pull/85
- https://github.com/openshift/cluster-api-provider-aws/pull/315
- https://github.com/openshift/cluster-api-provider-azure/pull/122
- https://github.com/openshift/cluster-api-provider-openstack/pull/108
- https://github.com/openshift/cluster-api-provider-baremetal/pull/81
- https://github.com/openshift/cluster-api-provider-ovirt/pull/55
- https://github.com/openshift/machine-api-operator/pull/571

OCPCLOUD-492: Leader election for machineSets, nodelink, vsphere and healthchecks

---

pkg/apis/machine/v1beta1/machine_types.go
pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go
pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go
pkg/controller/machine/machine_controller_suite_test.go
pkg/controller/machine/machine_controller_test.go

With #608 we dropped the burden from the user to set the clusterID label on machines.
As elaborated in https://github.com/openshift/machine-api-operator/pull/608#issuecomment-638772630 the motivation is that this is an implementation detail that users shouldn't care about.
However as the labels are used by machineSet to determine ownership, the change introduced above might result in edge scenarios where the machineSet and machine label has a different value. This would result in machines going orphan and the machineSet recreating new instances. Bad.
Therefore we choose now to remove the burden from users by enforcing the label value via webhhooks and keeping the old behaviour in the backend to avoid any chance of breaking existing environments where bad input might have been set as in …

Bug 1857175: enforce clusterID label via webhook and preserve old behaviour in the backend

---

pkg/operator/sync.go

`waitForDeploymentRollout` is crashing MAO pod, when there is an error during
the initial `.Get` request, attempting to read `d.GetName()` from an empty resource

Fix panic in deployment rollout, if it was accedentially removed

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go
cmd/vsphere/main.go
pkg/operator/sync.go

The machine-api-controller components are refreshing their lease more
than all other components combined. Bringing this to 90s each, will
decrease etcd writes at idle.
All relevant PRs:
- https://github.com/openshift/cluster-api-provider-aws/pull/339
- https://github.com/openshift/cluster-api-provider-azure/pull/152
- https://github.com/openshift/cluster-api-provider-baremetal/pull/88
- https://github.com/openshift/cluster-api-provider-gcp/pull/104
- https://github.com/openshift/cluster-api-provider-openstack/pull/109
- https://github.com/openshift/cluster-api-provider-ovirt/pull/56
- https://github.com/openshift/machine-api-operator/pull/649

BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle

---

pkg/operator/operator.go

This #535 introduced support to manage a damonSet which runs termination handler for spot intances.
As an event handler is not passed to the damonSet informer changes to the resource won't trigger a reconcile.
This PR fixes that by passing the event handler to the daemonSet namespaced informer.
This will be e2e tested by openshift/cluster-api-actuator-pkg#177

Fix terminationhandler sync

---

install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml

Update the CRD for BareMetalHost to the version that includes bootMode
and rootDeviceHints, 2 features added for the 4.6 release.

update the baremetalhost crd for bootmode and rootdevicehints

---

install/0000_90_machine-api-operator_03_servicemonitor.yaml

Enables functionality introduced in https://github.com/openshift/machine-api-operator/pull/590
Depends on 
- https://github.com/openshift/cluster-api-provider-baremetal/pull/77
- https://github.com/openshift/cluster-api-provider-openstack/pull/106
- openshift/cluster-api-provider-gcp#96
- openshift/cluster-api-provider-azure#136
- openshift/cluster-api-provider-aws#324
Demo:

Enable prometheus metrics for controllers

---

pkg/operator/sync.go

Currently the mao only validate the expected pods are available if there happens to be a deployment resource update https://github.com/openshift/machine-api-operator/blob/master/pkg/operator/sync.go#L110-L116.
This prevents the operator from going degraded for any scenario where the expected pods are not available and "ApplyDeployment" is not returning "updated=true".
E.g an induced pod crash looping.
Intead we want to wait to roll out the expected replicas every sync loop.
This was realised by https://bugzilla.redhat.com/show_bug.cgi?id=1856597

BUG 1859221: Wait for resources to roll out on every sync

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

This enabled webhooks to enforce the clusterID labels on machineSet/machine creation https://github.com/openshift/machine-api-operator/pull/644.
To avoid any difficult to predict side effect we want to honour any existing value that is already set on existing resources.

bug 1857175: Let webhook only set clusterID label if it does not exist

---

install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
pkg/operator/sync.go
pkg/operator/sync_test.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
vendor/modules.txt

The installer team is investigating running CI for AWS GovCloud https://issues.redhat.com/browse/CORS-1315 . Because of various restrictions the team and DPP are working to enable Gov Cloud emulator from SHIFT https://issues.redhat.com/browse/DPP-4708 as our solution to testing these restricted environment on AWS.
The SHIFT emulator works almost like Man-In-Middle-Terminating SSL Proxy capturing and transporting all connections from the chosen VPC to their own backbone and then emulating the AWS calls to say GovCloud region onto the source VPC's region which can be any commercial region.
So the allow testing of ipi workflow in the above mentioned environment we need the machine-controller talking to aws apis like other operators and components pulling content from internet to trust the …

add trusted ca bundle to machine-controllers

---

pkg/apis/machine/v1beta1/machine_webhook.go

This https://github.com/openshift/installer/pull/3730 changed the name of the userdata generated by the installer to satisfy MCO ign v2 -> v3 migration and let the new secret be under mco management. https://github.com/openshift/enhancements/pull/368.

Update default user data to be worker-user-data-managed

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

This tries to fix the following scenario:
We set ms.Spec.Selector.MatchLabels[MachineClusterIDLabel] if it's not present. It's not present and we set it to the correct value. If there happens to be a bad label in `ms.Spec.Template.Labels` this would result in a miss match.
Follow up for
https://github.com/openshift/machine-api-operator/pull/608,
https://github.com/openshift/machine-api-operator/pull/644 and
https://github.com/openshift/machine-api-operator/pull/653.

Set default clusterID labels only on machine

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go

Units are mandatory when a time.Duration is being parsed. The regex as it was allowed durations to be optional, this has been updated to force a unit to be included.

BUG 1865779: Ensure MHC duration fields include units

---

pkg/metrics/metrics.go

While reading through a bug that involved metrics, I noticed that this was updating the wrong metric variable.
There are no tests around this as far as I can tell, so I haven't updated any.
We should add some tests around the prometheus metrics, though I assume that would be in the E2E suite rather than here.

RegisterFailedInstanceUpdate should update failedInstanceUpdateCount

---

pkg/controller/nodelink/nodelink_controller.go
pkg/controller/nodelink/nodelink_controller_test.go

If node get deleted, nodelink controller will [remove the nodeRef](https://github.com/openshift/machine-api-operator/blob/master/pkg/controller/nodelink/nodelink_controller.go#L261-L262) from the machine.
It will happen only if there's something that delays the deletion, such as node finalizer. Otherwise, nodelink controller won't be notified that the node was deleted.
It means that we could reach different outcome, depends on the time taken for a node to be deleted.
If node was deleted immediately - nodeRef will stay on the machine.
If there's some delay (e.g. due to finalizer) - nodeRef will be deleted
It can also create a race with providers who put finalizer on the node, then can't determine which machine was associated with that node (see …

Bug 1866719: Keep machine.nodeRef even if node was marked for deletion

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

Add minimal disk value to webhook
https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#minimum-resource-requirements_installing-vsphere
Add default values for number of CPUs, memory and disk size
https://github.com/openshift/installer/blob/0ceffc5c737b49ab59441e2fd02f51f997d54a53/pkg/asset/machines/worker.go#L134

Bug 1861974: [vSphere] Improve vSphere webhook

---

install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
pkg/operator/baremetal_config.go
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/sync.go

In addition to supporting fully managed provisioning networks with the
option of having external DHCP servers, baremetal installations should
also be able to support cases where a dedicated provisioning network
does not exist.
Details regarding the updates to the provisioning CR to accomodate the
above feature can be found in [1].
Also, removing support for the ConfigMap as way to pass provisioning
configuration to the MAO for baremetal installs.
[1] - https://github.com/openshift/enhancements/blob/master/enhancements/baremetal/baremetal-provisioning-optional.md

Add support for optional provisioning networks on Baremetal platforms

---

pkg/operator/baremetal_pod.go

When the provisioning network is disabled, provisioning IP is on a
machine network, and we automatically detect the interface to use. We
need to pass the IP into these containers, as well as the interface (if
any is set).

baremetal: configure containers with provisioning_ip

---

go.mod
go.sum
pkg/apis/machine/v1beta1/machinehealthcheck_types.go
vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
vendor/modules.txt

This fixes the Defaulting and Validating webhooks so that they are aware of the new projectID within the NetworkInterface structure with the GCP providerSpec

BUG 1867262: Bump GCP provider dependency to include projectID field in NetworkInterface

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Previously, we were producing a remediation restricted event every reconcile if a maxUnhealthy value is negative.
We can only validate the maxUnhealthy integer value by creating a webhook which is a substantial amount of work, this is a quicker fix that makes the behaviour of a negative value identical to that of a 0 value.

BUG 1862556: Ensure that negative values for maxUnhealthy do not produce events

---

hack/fetch_ext_bins.sh
install/0000_30_machine-api-operator_03_machineset.crd.yaml
pkg/apis/machine/v1beta1/machineset_types.go

The docs say that this should be defaulted to 1. The controller expects it to be non nil and errors if the value is nil. By defaulting to 1 we may break a small number of users who may have been using a nil value to prevent the machineset controller from working, but this is not an intended behaviour anyway.
I have manually tested this on an openshift 4.6 cluster build from 2020-08-03 and it works as expected.

BUG 1827307: Default MachineSet replicas to 1

---

pkg/operator/baremetal_config.go
pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/sync.go

Changes to accommodate Baremetal UPI deployments or assisted baremetal deployments where the platform type would be Baremetal without a need to deploy the metal3 pod.

Bug 1840782: Update conditions under which metal3 pod would be deployed

---

pkg/operator/baremetal_pod.go
pkg/operator/baremetal_test.go
pkg/operator/operator.go
pkg/operator/sync.go

In an upgrade scenario, check if CBO is available to take ownership of the metal3 deployment. In that case, back off and let cluster-baremetal-operator (CBO) manage it.
In a downgrade/rollback scenario where the metal3 deployment is
annotated as being owned by cluster-baremetal-operator, but the CBO
has been removed, take back control of the metal3
deployment.

Bug 1873234: Manage ownership hand-off of metal3 between MAO and CBO for upgrade and downgrade

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

To improve the user experience of the MHC, we should always emit an event when we are skipping remediation.
We used to have this for master Machines, though this was removed when we migrated to the controller owner check (#543). This restores the behaviour, but with a new event that is more agnostic of the type of Machine.

BUG 1874861: Ensure an event is emitted when remediation is skipped

---

pkg/operator/status.go

The progressing condition is intedned to imply that a new version of the operator's resources are being rolled out. Currently we set it to resync on every reconcile which leads to constant updates and the value of the condiiton being unstable.
This change ensures that the status is stable when a version upgrade is not progressing and that we don't update the status every time we sync.

Bug 1855839: Ensure Progressing condition is stable when no updates to apply

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Add check for template disk size with tests.
Prevents user from hitting an undescriptive error message `invalid operation for device '0'`,
while attempting to create a machine from a template with a specified disk size larger
then the `machine.spec.diskGB` is requiring.

Bug 1875939: vsphere - cloning a Windows 2019 (1909) template fails with Invalid operation for device '0'.

---

install/0000_90_machine-api-operator_04_alertrules.yaml

Currently, the alert timing is too aggressive and
severity is too high.  An individual machine being
down is not critical, any critical components already
have alerting configured (such as etcd).
We're choosing 60m here to allow for MachineHealthChecks and
ClusterAutoscaler to clean up any failed machines prior to setting
an alarm for an individual machine.  This will prevent flapping
alerts on clusters.  Bare metal clusters may take up to 45 minutes
to provision machines depending on environment, so 60M should
cover those users as well.
Related Issue: https://issues.redhat.com/browse/OCPCLOUD-842
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1829138#c5

Bug 1878204: Adjust alert timing and severity

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

When a cluster that was first created via UPI the clusterID tag is missed in the vCenter.
This causes the machine controller to create the instances but failing and breaking the loop before being able to reconcile the status appropriately resulting in the machine resource having an inconsistent status which does not reflect reality.
`github.com/vmware/govmomi` misses typed errors, so the only way to not fail reconciliation on not found tag is iterate through the list of all tags and try to find clusterID tag. We assume the tag is always present in IPI.

Bug 1877281: [vSphere] Don't fail when tag is not found

---

pkg/controller/machine/controller.go

These two log messages were inconsistent with the format of all the others. In particular it is very confusing to see the message `deleting node <machine name> for machine`.

Bug 1878880: Fix confusing log messages about deleting Node

---

pkg/controller/vsphere/reconciler.go

Current log line does not display a task id because
it is not populated in status at this point.
This uses correct task id.

Bug 1880110: Vsphere: fix clone task log

---

pkg/apis/machine/v1beta1/machine_webhook.go

If a user were to modify this port manually (it defaults to 443), then this would break the webhook communication. We should ensure that it is always pointing to the right port.

Bug 1870158: Enforce webhooks service reference to port 443

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

This ensures that if the Machine goes into a Failed state, and the provider has already set the providerStatus to include an instanceState or vmState, that we override this with the value `Unknown`.
This ensures consistency between the providerStatus and the instance state annotation.
Ref:
- AWS: https://github.com/openshift/cluster-api-provider-aws/blob/9d3a7be556787c235a964fd72fdaec31af7a16ad/pkg/apis/awsprovider/v1beta1/awsproviderstatus_types.go#L36
- Azure: https://github.com/openshift/cluster-api-provider-azure/blob/72169c58a81f33ac006e20c63f643c9d8bf16771/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go#L38
- GCP: https://github.com/openshift/cluster-api-provider-gcp/blob/9056dbc8c9b9725fe13e2268ac8b0699c057d315/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus …

BUG 1875598: Ensure the Virtual Machine provider state is set to Unknown when Failed

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

This should allow our validation/defaulting webhooks to respond with some of their validations as warnings rather than errors.
The webhooks have been provided opinionated defaults and requiring these in validation. This may cause issues for existing users and as such, we need to reel back on these changes and ensure that we only error when a value is missing that would cause a Machine to not be created successfully.
This PR should reduce the opinionation and ensure that we don't break any existing installations

Bug 1876680: Reduce influence of webhooks and convert some errors to non-fatal

---

pkg/apis/machine/v1beta1/machine_webhook.go

This reverts commit 765b29ba00be5db02673bbb5e22e0229a94c43ff following findings in https://docs.google.com/document/d/1TnnfPgFim-e895MD0msOGN9tyPBk3CM8cmSewFmgzDQ/edit# and https://bugzilla.redhat.com/show_bug.cgi?id=1881703

Bug 1881703: Revert "Update default user data to be worker-user-data-managed"

---

cmd/vsphere/main.go
pkg/controller/vsphere/actuator.go
pkg/controller/vsphere/actuator_test.go

After patching the machine object following the initial
create, the subsequent reconcile may have a stale machine
object.  Additionally, any transient k8s API erros might
result in the patch operation failing and there is no
way to recover that operation. Either of these
scenarios will result in a double creation event
and a leaked instance.
This commit ensures we persist the taskID from the
vSphere API in case of this situations and preserve
it to ensure we do not double create.

Bug 1880110: vSphere: preserve taskID in local cache

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go
cmd/vsphere/main.go
pkg/operator/sync.go

This change brings in several cherry picks for the leader election mechanisms for all the controllers in this repo.
3d3b575168713c08cc803e41b2b60a6848e41ae9
c939c9208557c35a446d4217e5a4d3ea7de9caf7
5fdd6efbccb119d4805c373c959330242bbd6e67
48d9cce5d878be8b45f1d4b6df0345cee0d7593b
fe7cbdc445c681292859752904012bebdd2c2a98
495f3e78
0a561840
3f124196
a52a7ec8
91251df9
303f931e
644ed9ae
d6ec8b6c
a72ad436
fda33fd1
because this merge request will change the way that the controllers are deployed (adding leader election command line flags), we should make sure all the providers have the change in place first.
aws: https://github.com/openshift/cluster-api-provider-aws/pull/342
azure: https://github.com/openshift/cluster-api-provider-azure/pull/156
baremetal: …

Bug 1864352: Add leader election mechanism to release 4.5

---

pkg/controller/machine/controller.go
pkg/metrics/metrics.go

This PR adds a metric which tracks the phase transitions for Machines as they are transitioning to `Provisioning`, `Provisioned`, `Running` or `Failed`. This will allow us to calculate, for example, what the average creation time for a Machine is and see which phases are particularly slow.
Eg, the average time it took for a machine to enter each of these phases:
Since this is a histogram, we should be able to create some interesting graphs in Grafana once this is merged to allow customers to track how long different phases are taking
Potential future work: If we could get the MCS to serve the same metric and set an imaginary phase for `IgnitionFetched`, we could also see how long the Machine took to get to fetching ignition config.

[OCPCLOUD-910] Add HistogramVector to track transition into different Machine phases

---

docs/dev/metrics.md

Added section to the documentation explains typical use-cases these metrics should cover.

Add documentation section for 'mapi_instance_OP_failed' metrics

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go

[According to the enhancement proposal](https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/machine-instance-lifecycle.md#failed), Machine API providers should put the Machine into the `Failed` phase if the configuration is invalid. This was not working for the vSphere provider, due to the correct error being dropped in the error handling chain. This change ensures that the vSphere provider will behave consistently with the other providers in the event of invalid configuration.

vSphere: Enter Failed phase on invalid configuration

---

hack/gen-crd.sh
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_00_namespace.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
install/0000_30_machine-api-operator_04_metal3provisioning.crd.yaml
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
install/0000_30_machine-api-operator_08_webhook_service.crd.yaml
install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
install/0000_30_machine-api-operator_10_service.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
install/0000_30_machine-api-operator_12_clusteroperator.yaml
install/0000_90_machine-api-operator_03_servicemonitor.yaml
install/0000_90_machine-api-operator_04_alertrules.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

install/0000_30_machine-api-operator_03_machineset.crd.yaml
pkg/apis/machine/v1beta1/machineset_types.go

Fix a broken link in the description so that `oc explain` gives users a helpful description

Bug 1876469: Fix link on MachineSet Spec Metadata description

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/metrics/metrics.go
pkg/operator/baremetal_pod.go
pkg/operator/sync.go

* Refactor some of the proxy container setup so it can be reused.
* Add a metal3-metrics Service
* Add a metal3 ServiceMonitor

Bug 1820083: configure metal3 metrics collection

---

Makefile
hack/go-gen.sh
hack/update-codegen.sh
hack/verify-diff.sh

This PR is dependent on openshift/release#13400 to enable the functionality in CI. Should go prior to the PR, allowing CI to get green.
Changes:
- Check file diff between committed code and generated bits with hack/verify-diff.sh
- go generate is moved into it's own script, which uses docker image with goimports tool in it - hack/go-gen.sh

[OCPCLOUD-809] Add verify-diff check in generate task and enable in CI

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go

Disconnected installations are using different DNS settings, and this is displayed in the resource
```yaml
apiVersion: config.openshift.io/v1
kind: DNS
metadata:
name: cluster
spec:
baseDomain: ***
privateZone:
id: <id>
publicZone: <- this field is absent in disconnected install
id: <id>
```
The PR goal is to reject an invalid MachineSet configuration when a `publicIP: true`, to prevent Machine from failing.

Bug 1889620: Azure disconnected reject publicIP setting

---

install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_09_security_context_constraint.yaml
install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
pkg/operator/sync.go

This PR switches the spot termination handler to use conditions instead of deleting machines directly.
This will require counter PRs in each provider repository to update the termination handler there as well.
Considerations:
- This deploys a MachineHealthCheck that will be present on all clusters going forward that explicitly allows spot instances to be deleted immediately when the terminating condition is applied. This means it will potentially conflict with autoscaling as described [here](https://github.com/openshift/enhancements/pull/330/files#diff-0dd209ee156555586b5e7700cb4bacf9R95-R107)
- This deploys a new SCC to all clusters, this may not be desirable. The alternative is to use the `privileged` SCC but this gives us far more permission that we need
- This will now use Kubelet …

[OCPCLOUD-937] Update resources to allow termination handler to apply conditions

---

cmd/machine-api-operator/start.go
docs/user/cluster-wide-proxy.md
install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/baremetal_test.go
pkg/operator/config.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

- What I did
Inject proxy environment variables in to the deployment for the machine-api-controller when a cluster-wide proxy is configured.
- How to verify it
1. Configure cluster-wide proxy
2. `machine-api-controller` deployment will be updated to inject HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables.
3. Check proxy logs to confirm requests are flowing through the proxy
- Description for changelog
Inject cluster-wide proxy configuration in to machine-api-controller deployment

Bug 1896704: Inject cluster-wide proxy configuration in to machine-api-controller deployment

---

pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

Follow up on https://github.com/openshift/machine-api-operator/pull/746, adding missing disconnected setting on MachineSet.
The previous implementation was rejecting Machines, with error event in logs:
```
2m5s        Warning   ReconcileError      machineset/miyadav-b9620-4wrtx-worker-pubip           failed to sync machines: admission webhook "validation.machine.machine.openshift.io" denied the request: providerSpec.publicIP: Forbidden: publicIP is not allowed in Azure disconnected installation
```
Fixed behavior will create only a warning on Machine creation, but will not make the operation to fail.

Bug 1889620: Warn MachineSet with publicIp set in disconnected install

---

install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
pkg/apis/machine/v1beta1/machine_types.go
pkg/apis/machine/v1beta1/machineset_types.go

This change removes some comments that are creating extra information in the generated descriptions for some of the CRDs. It also regenerates the all the necessary files.

Bug 1895838: Remove extraneous code comments

---

cmd/machine-api-operator/start.go
docs/user/cluster-wide-proxy.md
install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/baremetal_test.go
pkg/operator/config.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go

This is a cherry-pick of #725 
This updates MAO to honour cluster wide proxy settings and inject the required environment variables into containers within the machine-api-controllers deployment

[release-4.6] Bug 1896705: Inject cluster-wide proxy configuration in to machine-api-controller deployment 

---

cmd/machine-healthcheck/main.go
docs/dev/metrics.md
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/metrics/machinehealthcheck.go
pkg/metrics/metrics.go

This change adds a gauge metric to record the nodes covered by MHCs, it
also adds a helper function to make setting this value more convenient.

add mapi_machinehealthcheck_nodes_covered metric

---

docs/dev/metrics.md
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/metrics/machinehealthcheck.go

This change adds a counter metric for successful remediations, it also adds a helper function to increase the counter and documentation about the new metric.

add mapi_machinehealthcheck_remediation_success_total metric

---

hack/push-updates.sh
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This PR is part of task done to add KubeVirt platform as infra provider for Openshift.
The change introduced in this PR purpose is to provide a way to install Openshift on KubeVirt infrastructure
For more information, please find the enhancement PR:
openshift/enhancements#417
Related PRs/changes done as part of this task:
1. Created openshift/cluster-api-provider-kubevirt repository, hosts an implementation of a provider for KubeVirt for the OpenShift machine-api: https://github.com/openshift/cluster-api-provider-kubevirt
Also adding this project's image to openshift is in progress
2. openshift/installer: https://github.com/openshift/installer/pull/4350
3. openshift/cloud-credential-operator: openshift/cloud-credential-operator#260
4. openshift/machine-config-operator: …

Add Kubevirt provider

---

install/0000_30_machine-api-operator_09_rbac.yaml

This doesn't work if you spell it wrong. This is needed to ensure the security policy matches (ie no secret mounting).
Pods currently can't schedule as the pod is trying to mount a secret which we haven't allowed.

Bug 1902157: Fix spelling of automountServiceAccountToken

---

pkg/apis/machine/v1beta1/machinehealthcheck_types.go

So long as the value has been non-zero before, this will ensure that the value is printed. If it has never been non-zero, it's very difficult for us to set the field without making it a pointer, which we would preferably not do as it complicates a lot of logic throughout the codebase.

Bug 1902253: Ensure zero value of remediationsAllowed is printed

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

When Machines go into the Failed phase, this is permanent. Their actuators' `Update()` methods are never called again, and the actuator doesn't get another chance to run until the Machine is deleted. Therefore Machines in this phase cannot be externally remediated by the Machine actuator.
Currently baremetal Machines are the only ones using external remediation, and currently they never go into the Failed phase, but in the future we would like to use this phase to handle unrecoverable errors (invalid config, underlying Host was deleted, &c.)
In these cases, rebooting will not help, and the actuator does not get called to enable it do try anyway, so always remediate them by
deleting the Machine.

Don't use external remediation on failed Machines

---

pkg/controller/machine/controller.go

Set retry timeout for actuator.Update() failures in order to avoid exponential backoff for slow providers.

Bug 1880161: Set retry timeout for actuator.Update() failures

---

install/0000_30_machine-api-operator_09_rbac.yaml

Some context: The Baremetal platform has a requirement to pass full ignition to the hosts prior to their deployment. We do this to go around the chicken-and-egg issue in situations where more advanced network configurations such as interfaces on vlans and/or bonds need to be configured before the node is deployed. We can access the machineconfigserver (MCS) from everywhere except within the pod network. 
This PR updates the RBAC to enable the machine-api-controllers to gain access to machineconfig and machineconfigpool objects. This is done to enable the baremetal platform's controller, cluster-api-provider-baremetal (CAPBM) to fetch the rendered ignition from the machine-config-operator instead of the MCS. The CAPBM uses this ignition information to create a new secret which is then …

Update RBAC to enable access to machineconfig object for the baremetal controller

---

docs/dev/metrics.md
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/metrics/machinehealthcheck.go

This change adds the counter metric to track when a MachineHealthCheck
has been short-circuited. It adds helper functions for enabling and
disabling the metric, and an update to the metrics doc showing the new
metric.

add mapi_machinehealthcheck_short_circuit metric

---

install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_09_security_context_constraint.yaml

I thought last PR was the last one. Sorry for the noise.
A check in the CI will be soon available.

Add missing default cluster profile annotation

---

cmd/vsphere/main.go

That is a manual cherry-pick. Its purpose is to reduce the sync period to 10 minutes in order to better reflect the real state of vSphere VMs.

Bug 1869320: [release-4.5] [vSphere] Reduce sync period to 10 minutes

---

pkg/operator/sync.go

@joelddiaz @michaelgugino 
Add a projected service account token to the machine-controller container in the machine-api-operator pod.  We will use this token to get STS creds when that is wired in.
This is inert until then.
https://issues.redhat.com/browse/CO-1254 subtask https://issues.redhat.com/browse/CO-1274

add bound serviceaccount token to machine-controller

---

hack/fetch_ext_bins.sh
pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/controller/vsphere/reconciler.go

If the user forgets to specify CPU, memory, or disk size we default it to 0 and the reconciler then defaults it to a minimal value.
This PR:
1. Make webhook return warning on missing VM specs
2. Removes defaulting from the controller and let's fail to pass.

Bug 1882723: vSphere: Create warning on invalid specs and remove defaults

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go
pkg/apis/machine/v1beta1/v1beta1_suite_test.go

This let the webhook to validate the credentialsSecret existence before creating the machine resource.
Additionally we should probably reflect any unexpected error to use the credentialsSecret as providerStatus conditions https://issues.redhat.com/browse/OCPCLOUD-931
I'm taking over this bug from @enxebre as he is away for three weeks. I've applied all of my suggestions from the original PR #660 and am happy for this to merge once it has undergone some manual testing.

Bug 1805639: Validate credentialsSecret

---

pkg/controller/machineset/delete_policy.go
pkg/controller/machineset/delete_policy_test.go

See: https://bugzilla.redhat.com/1903733

Bug 1903733: MachineSet: Prefer to delete non-Running machines during scale down

---

pkg/operator/sync.go

The Kube RBAC Proxy containers are logging excessively. Having log level 10 includes logging bearer tokens and full http request/responses. This is insecure, more logging than we need, and has an impact on aggregated logging. Reduce to 3 to be inline with other components.

Bug 1907380: Reduce verbosity of kube-rbac-proxy logging

---

pkg/controller/machine/controller.go

Any pod having a long gracePeriod will block drain for that length of time on unreachable kubelets, and this is undesirable.  This is because a pod's deletionTimestamp is not a timestamp which indicates when it was marked deleted (as assumed), rather it's the deadline of some future time (if utilizing a gracePeriod) for the kubelet to send SIGKILL.
We want pods to be drained quickly on unreachable kubelets are we're intended to remove the machine in our case, we don't need to wait for them to come back.  PDBs are still honored and any pod covered by a PDB is not affected by this change.  Kubelets that are not unreachable are not impacted by this change.
More discussion here: https://bugzilla.redhat.com/show_bug.cgi?id=1905709#c13

Bug 1905709: Drain: ignore gracePeriod on unreachable kublets

---

install/0000_30_machine-api-operator_11_deployment.yaml

The Kube RBAC Proxy containers are logging excessively. Having log level 10 includes logging bearer tokens and full http request/responses. This is insecure, more logging than we need, and has an impact on aggregated logging. Reduce to 3 to be inline with other components.

Bug 1907380: Reduce verbosity of kube-rbac-proxy logging for operator

---

hack/gen-crd.sh
install/0000_30_machine-api-operator_00_namespace.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_01_trusted-ca-configmap.yaml
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
install/0000_30_machine-api-operator_08_webhook_service.crd.yaml
install/0000_30_machine-api-operator_09_rbac.yaml
install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
install/0000_30_machine-api-operator_10_service.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
install/0000_30_machine-api-operator_12_clusteroperator.yaml
install/0000_90_machine-api-operator_03_servicemonitor.yaml
install/0000_90_machine-api-operator_04_alertrules.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all machine-api-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

install/0000_30_machine-api-operator_13_machinehealthcheck.yaml

Until we switch to cluster profiles for ROKS, we still need to exclude manifests that do not apply. The MachineHealthCheck CRD is not defined in a ROKS cluster.

Bug 1915962: Add exclusion annotation for machine health check on ROKS

---

install/0000_30_machine-api-operator_09_rbac.yaml

To support custom CA bundles for AWS, the machine-api-controllers need access to the kube-cloud-config ConfigMap in the openshift-config-managed namespace.

Bug 1915114: allow machine-api-controllers to access configmaps in openshift-config-managed

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

When an error returned by the actuator causing the Machine to enter the
Failed phase is of a known type, record the type in the ErrorReason
field.
In the upstream cluster-api, permanent failures were signalled by the
actuator setting the ErrorMessage and ErrorReason fields. A separate
controller reads these fields and updates the Phase.
In the OpenShift implementation
(176084ee02b546e1750a70d392190b7134694dac) this is signalled by the
actuator returning a MachineError, which contains the message and the
reason. However, the Machine controller was ignoring the reason so it
was never set.

Machine: Set ErrorReason when entering Failed phase

---

pkg/controller/vsphere/reconciler.go

We should never pass an empty string into `handleVSphereError` as it may result in error messages being returned such as `ocp4-llplx-windows-qs6cx error: ocp4-llplx-windows-qs6cx: reconciler failed to Create machine: ` which isn't helpful for debugging.
There has been some conversation and debugging around a potential bug that seems to be coming from this piece of the code, so we should make sure that we are returning useful errors, even in cases that seem unlikely.

Return a valid error message when multiple templates are found

---

README.md

The upstream version of cluster-api-provider-baremetal is deprecated,
so link to our fork.
Replaces #783
cc @tuananh
/cc @joelspeed

fix the link to capbm

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This change is done because of the desicion not to include this image in the release
because it defined in "dev preview" stage

Bug 1929645: Remove "kubevirt-machine-controllers" image from release 4.7

---

hack/ci-test.sh

Enables Junit reports for unit tests CI job. Currently  we have no info what tests were run and failures might looks like a mess.
Fixes https://issues.redhat.com/browse/OCPCLOUD-1093

Enable Junit reports for CI unit tests runs

---

pkg/operator/sync.go

We are ensuring that daemonset maxUnavailable is
set to 10% for rolling update strategy to conform
to platform standards.

Ensure daemonset conforms to standards

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

Manual cherry-pick of 
- https://github.com/openshift/machine-api-operator/pull/746
- https://github.com/openshift/machine-api-operator/pull/749

[release-4.6] Bug 1933676: Cherry-pick: Azure disconnected reject publicIP setting

---

install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

The default ciphers are not secure and are susceptible to a number of different known vulnerabilities. This collection of ciphers should be more secure and have no known vulnerabilities present.
Suites inspired by the [cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator/blob/f98cd6d7d1dc50fe881c6aa29d772a581451afd1/manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml#L54).

Bug 1923823: Improve TLS configuration for Kube RBAC Proxy

---

docs/user/Alerts.md
install/0000_90_machine-api-operator_04_alertrules.yaml

The cluster-version operator is responsible for complaining if the machine-API operator's deployment is sad, so no need for the operator to handle this directly (we end up doubling up if there's an issue).  This drops the alert which was added in 9b666d6f20 (#388).
See also openshift/cloud-credential-operator#308.  Also, I just saw MachineAPIOperatorDown in the wild during the recent build01 explosion.

install/0000_90_machine-api-operator_04_alertrules: Drop MachineAPIOperatorDown

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

For a new way of managing OpenShift credentials on AWS to work, using Security
Token Service, we need external tooling to know the service account names from
the Credentials Request manifest so that it can create IAM Roles that can be
assumed only by those specific service accounts.
Managing credentials using STS ref: https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
Tooling design ref: https://issues.redhat.com/browse/CCO-60
/cc @joelddiaz

Add service account names to credentials request manifest

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

The validating webhook for AWS will now throw a warning if the user does
not provide an IAMInstanceProfile with their AWSProviderSpec. Also adds
a unit test for this condition.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1932154

BUG 1932154: add warning for missing IAMInstanceProfile in AWS

---

pkg/operator/sync.go

We were relying on the service account to be updated before the daemonset was rolling out. But CVO does not guarantee the ordering of objects being rolled out when they are at the same runlevel. 
To avoid having to create ordering dependencies by using multiple run levels, we can instead specify not to mount the service account token directly on the pod spec
I've manually tested this on AWS and the deployment can roll out even when the service account hasn't been updated with this patch in plcase

Don't mount service account token in termination daemonset

---

pkg/apis/machine/v1beta1/machine_webhook.go

The webhook test started failing consistently for GCP because the default image that was being used does not support ignition v3. Update to a newer image (as used in the installer) so that the tests pass again

Update GCP default disk image to include ignition v3

---

docs/dev/hacking-guide.md

Building images with [openshift/imagebuilder](https://github.com/openshift/imagebuilder) might fail if user does not have docker-daemon running on their machine. Added instructions to the hacking-guide on how to overcome this issue.

Update hacking-guide.md with imagebuilder troubleshooting instructions

---

pkg/apis/machine/v1beta1/machine_webhook.go

There's a typo in the image name which means it's not currently working

Fix GCP default image name

---

cmd/vsphere/main.go
go.mod
pkg/controller/vsphere/machineset/controller.go
pkg/controller/vsphere/machineset/controller_suite_test.go
pkg/controller/vsphere/machineset/controller_test.go
vendor/github.com/onsi/ginkgo/extensions/table/table.go
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
vendor/modules.txt

This PR adds a new controller to annotate machinesets with information required to enable autoscaling to/from zero based on providerSpec input based on openshift/enhancements#186.
Analogous to openshift/cluster-api-provider-aws#301, openshift/cluster-api-provider-azure#112 and openshift/cluster-api-provider-gcp#77.

Vsphere enable autoscaling from/to zero

---

install/0000_30_machine-api-operator_09_rbac.yaml

Without annotations, it appears CVO ignores the ClusterRole. Need to add these annotations and verify that CVO is in fact creating the ClusterRole

Bug 1948471: Add release inclusion annotations to external remediation cluster role

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This permission was missing in minted credentials.
```
E0326 12:16:56.376058       1 loadbalancers.go:117] Failed to unregister instance "i-06828db8c6de8ac53" from target group "arn:aws:elasticloadbalancing:us-east-2:301721915996:targetgroup/miyadav-aws-26-sq5k5-aext/e7b92a1a0249694a": AccessDenied: User: arn:aws:iam::301721915996:user/miyadav-aws-26-sq5k5-openshift-machine-api-aws-c5bws is not authorized to perform: elasticloadbalancing:DeregisterTargets on resource: arn:aws:elasticloadbalancing:us-east-2:301721915996:targetgroup/miyadav-aws-26-sq5k5-aext/e7b92a1a0249694a
status code: 403, request id: 931605e3-1b43-457f-858b-8f896cfc33fd
E0326 12:16:56.376099       1 reconciler.go:342] miyadav-aws-26-sq5k5-master-2: Failed to register network load balancers: …
```

Bug 1880757: Add missing permission for target group de-registration

---

pkg/controller/machine/controller.go

If we don't do a deepcopy, because the conditions list is a reference type, our new variable will be overwritten by the below update to annotations when the Machine is entering a Failed state. This results in weird mixed conditions.
I've manually tested this change on AWS and it now works as expected.

Bug 1910318: Ensure conditions are correctly copied before annotations are patched

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

Fixed all missing places where context was not passed to client call or draining call.
Fixes this panic in draining as node update requires context to be passed:
```
I0416 15:31:44.531825       1 machine_scope.go:102] ci-op-06xhm87t-34603-vts6z-worker-hpnrd: patching machine
I0416 15:31:44.531960       1 recorder.go:104] controller-runtime/manager/events "msg"="Normal"  "message"="Updated Machine ci-op-06xhm87t-34603-vts6z-worker-hpnrd" "object"={"kind":"Machine","namespace":"openshift-machine-api","name":"ci-op-06xhm87t-34603-vts6z-worker-hpnrd","uid":"19099d27-ae2b-42f4-a5e0-7b567ba03f27","apiVersion":"machine.openshift.io/v1beta1","resourceVersion":"40829"} "reason"="Update"
I0416 15:31:44.566238       1 controller.go:174] ci-op-06xhm87t-34603-vts6zvcp6t-sjxkf: reconciling Machine …
```

Bug 1951029: Drainer panics on missing context for node patch

---

install/0000_30_machine-api-operator_00_namespace.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

pkg/apis/machine/v1beta1/machine_webhook.go

4.7 clusters set up an ignition v3 stub, which doesn't work with the default 4.6 image as it supports v2.2 as a maximum version.
This should fix the defaulting and in turn, the broken GCP operator suite.

Bug 1954610: Update GCP default image to match 4.7 release

---

pkg/operator/operator.go

This filter is meant to check if either mutating or validating webhooks are modified, except it was checking for mutating webhooks twice. This meant that our operator wasn't actually reacting to events triggered by validating webhooks.
This explains why the validating webhook tests are so flaky and take a long period to complete even when they do pass.

Bug 1955554: Webhook filter should check for both mutating and validating webhooks

---

pkg/apis/machine/v1beta1/machine_webhook.go

admissionReviewVersions v1beta1 is going to be removed in kubernetes
1.22, this change bumps the version from v1beta1 to v1.

Bug 1954177: update AdmissionReviewVersions to v1

---

pkg/apis/machine/v1beta1/consts.go

These constants were removed during a cleanup, but some of them are
being used by external dependencies. This change adds them back in
with the newer changes.

Bug 1954177: add constant variables back into machine v1beta1

---

install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
install/0000_30_machine-api-operator_13_machinehealthcheck.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go
pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

The spot termination handler MHC should only ever remove Machines that meet the spot termination condition. We do not want it to remove machines because they took too long to start up. That should be a user decision.
This PR adds the ability to disable the node startup timeout completely, and uses that for the spot termination MHC.

Bug 1939054: Disable startup timeout for Spot MHC

---

pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

As Infrastructure.Status.Platform is being deprecated, this change
switches the internal logic to look at
Infrastructure.Status.PlatformStatus.Type instead. Unit tests have been
adjusted, and an extra test for the deprecated value has been added.

Bug 1967662: change provider config to look at PlatformStatus.Type

---

README.md
docs/dev/hacking-guide.md

I believe this Dev instruction in the readme : 
- Create a `openshift-machine-api-operator` namespace
aught to be this namespace instead:
- Create a `openshift-machine-api` namespace
small update

Correct doc namespace err and misspellings

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This change is being created to address the removal of these artifacts in
the 4.8 release. After this change has been backported to 4.8 it should
be reverted for the 4.9 branch.
ref: https://github.com/openshift/ocp-build-data/pull/944

remove kubevirt images and references

---

docs/user/Alerts.md
install/0000_90_machine-api-operator_04_alertrules.yaml

This change adds the alert for a machine with phase "Deleting" for
longer than 180 minutes, at "warning" severity. Also updates the alerts
documentation with new information.
The MachineWithNoRunningPhase alert has also been modified to exclude
machines with the "Deleting" phase to ensure that we do not double fire
an alert for this condition.
ref: https://issues.redhat.com/browse/OCPCLOUD-921

[OCPCLOUD-921] add alert for machine with long deletion phase

---

Makefile
hack/go-mod.sh

Add option to run make vendor in container like other targets, to avoid issues with go module caching depending on what you already have on your machine.

add in-container vendoring

---

install/0000_90_machine-api-operator_04_alertrules.yaml

b13dbe9949 (#807) added `|Deleting`.  But to move from "not equal" to "regexp does not match" we need to match that with `!~`.
/assign @elmiko

install/0000_90_machine-api-operator_04_alertrules: Use '!~' for MachineWithNoRunningPhase

---

docs/examples/machine.yaml
pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

- aws: differentiate between X86 and ARM instance types
- aws: bump X86 default instance type to m5.large

Bug 1953063: Update default AWS instance types

---

install/0000_30_machine-api-operator_13_machinehealthcheck.yaml

Since the MachineHealthCheck object does not allow modifying default labels manually, hence I would like to fix this in it's resource yaml itself.

Fixing label from clutserapi to clusterapi

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This change re-adds the kubevirt images and tests to the
machine-api-operator. They were removed to enable a backport to the 4.8
release branch, in which those images were not shipped. This changeset
sets things back to the status quo.
ref: #873

Add kubevirt images

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/machine_scope_test.go
pkg/controller/vsphere/reconciler_test.go

Treat node as unreachable and proceed with vm deletion in case on vSphere if node object referenced in machine not found.

Bug 1977369: Prevent machine from stucking in Deleting phase on vSphere if related node object not found

---

install/0000_99_machine-api-operator_00_tombstones.yaml

CVO has added the ability to remove objects created in previous releases
of OpenShift. This change adds a manifest to remove old objects which
are no longer used by the machine-api.
ref: https://issues.redhat.com/browse/OTA-395

[OCPCLOUD-1153] add a tombstones manifest to the install directory

---

pkg/apis/machine/v1beta1/consts.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/util/annotations/helpers.go

With this PR we backport the pause annotation for MachineHealthCheck resources from upstream SIG Cluster API. It can be used for e.g. pausing remediation during cluster upgrades. See https://github.com/openshift/enhancements/pull/827
Upstream code:
https://github.com/kubernetes-sigs/cluster-api/blob/87270011c60fdd336949ad22dd1b3c59498b8480/controllers/machinehealthcheck_controller.go#L134
https://github.com/kubernetes-sigs/cluster-api/blob/a5e1b5fe003a29ec09a433cc5f6118e76993caa2/api/v1alpha4/common_types.go#L54

Backport MHC pause feature from cluster API

---

docs/user/Alerts.md
install/0000_90_machine-api-operator_04_alertrules.yaml

This adds an alert for when an mhc has been in short-circuit for more
than 30 minutes, also adds some documentation about it.
ref: https://issues.redhat.com/browse/OCPCLOUD-922

[OCPCLOUD-922] add alert for mhc in short circuit

---

cmd/machine-api-operator/helpers.go
cmd/machine-api-operator/start.go
cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go
cmd/vsphere/main.go
pkg/util/durations.go

According to [1] to successfully handle kube-apiserver disruption  we need to updated default durations for MAO leader election operations.
New values are LeaseDuration=137s, RenewDealine=107s, RetryPeriod=26s.
[1] https://github.com/openshift/enhancements/pull/832

Bug 1980930: Update the default durations for MAO leader election operations

---

install/0000_99_machine-api-operator_00_tombstones.yaml

This change adds the annotation
`include.release.openshift.io/self-managed-high-availability: "true"`
to the tombstones. This is needed to ensure that the CVO will process
them.

Bug 1988032: add cvo ha annotations to tombstones

---

pkg/controller/vsphere/actuator.go
pkg/controller/vsphere/actuator_test.go

Now vsphere actuator always creates an event after Update, even though the change might not have happened.
To prevent creating fake events we compare machine resource version before and after update, and create an event only if they are different.

Bug 1989980: Create event only if the machine was modified

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go

This commit checks if the node has some attached volumes before deleting its vm. If there are any, it doesn't allow to delete the vm and returns an error.

Bug 1990432: Make sure nodes don't have attached volumes before vm deletion

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go

Replaces #898 because Zane is on PTO
Applied suggested refactoring, added unit test
From the original PR:
Conventional remediation consists of simply deleting the Machine object.
In consequence, it was safe to consider that any Machines that do not
need remediation, have a Node, and are not in the process of being
deleted, are 'healthy'.
However, external remediation takes place not by deleting a Machine but
by adding an annotation to it. While the Machine continues to exist (and
may be associated with a Node for part of the time), it will not be in a
working state throughout the remediation (generally because they are
being rebooted).
Because these Machines were considered 'healthy', additional Machines
could be remediated during this process in violation of the MaxUnhealthy
limit. If …

Bug 1975296: Respect MaxUnhealthy limit for external remediation

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go

This will add a warning when a user sets multiple tag specifications which use the same Name. Our controller deduplicates these and uses the first value found, since only one tag specification can be sent to AWS.
I don't think we want to change that behaviour, so a warning to users should make it more obvious why they are not seeing the multiple tag values being set on AWS.

Bug 1957609: Warn when an AWS tag name is duplicated

---

pkg/apis/machine/v1beta1/machine_webhook.go
pkg/apis/machine/v1beta1/machine_webhook_test.go
pkg/apis/machine/v1beta1/machineset_webhook_test.go

Currently, only ID is used to reference an AMI https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/instances.go#L333 however we expose two other API fields - ARN and Filters. This PR adds a webhook to prevent users from using unsupported values.

Add webhook to ensure that only ID references AMI

---

pkg/controller/vsphere/session/session.go

For some reason vCenter using user-agent from first
login request and does not respect it's change after.
Moved login step into our code with setting user-agent
for soap client beforehand.
Info log message for new vCenter session creation added
by the way.
tested on vCenter 7.0.1.00200

Fix user-agent in vCenter sessions list

---

docs/user/Alerts.md

This change updates the MachineWithoutValidNode and
MachineWithNoRunningPhase alert documentation to have the proper time
length values.

fix time values in alert doc

---

docs/user/machine-api-operator-overview.md
pkg/operator/operator_test.go
pkg/operator/status.go
pkg/operator/sync.go

When the MAO is running on platforms it does not recognize it will be in
NoOp mode. This change adds a message to the operator status that
indicates this mode of operation, it also adds tests and documentation.

[OCPCLOUD-855] add a distinct status message for NoOp mode

---

install/image-references

Cannot be merged until the ibmcloud mapi controller image is available in the release payload.

Adds ibmcloud mapi controller to image ref

---

docs/user/nodelink-controller.md

A bit further up in the file we have:
machine.openshift.io/machine: openshift-machine-api/alpha-b6dhr-worker-us-east-2a-jxqng
which is namespace first.  Confirming in [4.8.2->4.8.3 CI][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1420413555873681408/artifacts/launch/nodes.json | jq -r '.items[].metadata.annotations["machine.openshift.io/machine"]' | sort
openshift-machine-api/ci-ln-zzbp4lb-d5d6b-zjbh9-master-0
openshift-machine-api/ci-ln-zzbp4lb-d5d6b-zjbh9-master-1
openshift-machine-api/ci-ln-zzbp4lb-d5d6b-zjbh9-master-2
openshift-machine-api/ci-ln-zzbp4lb-d5d6b-zjbh9-worker-us-east-2a-454fw
openshift-machine-api/ci-ln-zzbp4lb-d5d6b-zjbh9-worker-us-east-2a-b95ng …
```

docs/user/nodelink-controller: Fix name/namespace order for machine.openshift.io/machine

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

This change is done because of the desicion not to include this image in the release
because it defined in "dev preview" stage

Bug 2003545: Remove "kubevirt-machine-controllers" image from release 4.9

---

install/image-references

The ironic-inspector image was deprecated in 4.9 and removed in 4.10
We need this to fix the builds for 4.10 see [1]
We already removed from CBO in  openshift/cluster-baremetal-operator#196
[1] https://amd64.ocp.releases.ci.openshift.org/releasestream/4.10.0-0.nightly/release/4.10.0-0.nightly-2021-09-08-172131

Remove ironic-inspector reference in MAO

---

go.mod
go.sum
install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
pkg/apis/machine/v1beta1/machinehealthcheck_types.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go

This field is an int or string and as such should not specify the type to be a string, this can cause errors in the CRD conversion when upgrading as we have changed the underlying type. Removing `type: string` should resolve these upgrade errors.

Bug 1999425: MaxUnhealthy should not be a string type

---

docs/user/Alerts.md
install/0000_90_machine-api-operator_04_alertrules.yaml

Cherry-pick of #807 and #878, as CCX has noticed an uptick in MachineWithoutValidNode alerts on vsphere clusters recently

Bug 1999585: [release-4.8] add alert for machine with long deletion phase

---

pkg/controller/vsphere/session/session.go

Log possible error, which might be returned from `SessionIsActive` check.

Add logging for possible error during vsphere session creation

---

pkg/controller/vsphere/session/session.go

Improve log message:
before:
- E0923 17:00:20.257037   14509 session.go:68] Error performing session check request to vSphere: %!w(soap.soapFaultError={0xc0016a7270})
after:
- E0923 17:01:58.988560   14813 session.go:68] Error performing session check request to vSphere: ServerFaultCode: Permission to perform this operation was denied.

Vsphere sessions check: fix log string formatting

---

install/0000_30_machine-api-operator_00_namespace.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-machine-api` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for  openshift-machine-api namespace

---

docs/user/Alerts.md
install/0000_90_machine-api-operator_04_alertrules.yaml

This change makes it so that the alert will ignore changes in the `pod`
label during the duration of the alert. It is being added to account for
cases where the machine-api-operator pod might be rescheduled and thus
its pod name will change. This should allow the alert to persist.

Bug 1986237: modify MachineNotYetDeleted alert to ignore pod

---

Dockerfile

Update the Dockerfile to fix the registry.ci URL and bump the go version.

Update Dockerfile with correct image and go version

---

pkg/webhooks/machineset_webhook.go
pkg/webhooks/machineset_webhook_test.go

If a user were to modify the selector on a MachineSet, then it would no longer pick up the Machines originally selected by it (unless the Machines had already been updated). In this case, it will create new Machines, orphaning the old Machines.
To prevent this, we should deny updates to the selector once the MachineSet has been created. This will then mimic the behaviour of the built in types, eg Deployment, ReplicaSet, StatefulSet and DaemonSet.
Additionally, and inspired by the behaviour of the built in types, the second commit will prevent updates the mean that the selector will not match the labels of the Machines created by the MachineSet. This will prevent a hot loop of Machine creation where the MachineSet creates a Machine that it can't recognise via the selector.

Bug 2005052: Deny selector updates via webhook to prevent leaked machines

---

install/0000_30_machine-api-operator_01_images.configmap.yaml

Add the missing image entry for the PowerVS platform
The initial support is pushed via - https://github.com/openshift/machine-api-operator/pull/923

Add powervs-machine-controllers to images configmap

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Bug 2022838: GCP CI runs are complaining about APIs not being enabled

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Bug 2022840: GCP CI runs are complaining about APIs not being enabled

---

README.md

This PR:
- tries to improve the readability of the README Controllers section by aligning the indentation of the body of the Controllers entries
- updates the MachineHealthCheck and Nodelink Controllers in the README names to match more closely the CRD for one and the convention for the other

README: improve Controllers section indentation/naming

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Revendored [openshift/cluster-api-provider-gcp](github.com/openshift/cluster-api-provider-gcp) to update [`GCPMachineProviderSpec`](https://github.com/openshift/cluster-api-provider-gcp/blob/master/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go#L14) struct. 
Added validation for guest accelerators and appropriate associated default values.

OCPCLOUD-1252: Add validation webhook for guestAccelerators on GCP

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

The roles/compute.loadBalancerAdmin pre-defined GCP Role is listed as Beta:
```
[jdiaz@minigoomba ~]$ gcloud iam roles describe
roles/compute.loadBalancerAdmin | grep stage -B1
name: roles/compute.loadBalancerAdmin
stage: BETA
```
The desired permissions from that role revolve around
compute.targetPools.*.
roles/compute.admin provides compute.targetPools.* (and much more), and
it is not Beta.
```
[jdiaz@minigoomba ~]$ gcloud iam roles describe roles/compute.admin |
grep -E 'compute.targetPools|stage'
- compute.targetPools.addHealthCheck
- compute.targetPools.addInstance
- compute.targetPools.create
- compute.targetPools.delete
- compute.targetPools.get
- compute.targetPools.list
- compute.targetPools.removeHealthCheck
- compute.targetPools.removeInstance
- compute.targetPools.update
- …
```

Bug 2031858: stop using beta pre-defined role for compute.targetPools

---

go.mod
go.sum
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/fixtures/images.json
pkg/operator/operator_test.go
vendor/k8s.io/klog/v2/OWNERS
vendor/k8s.io/klog/v2/klog.go
vendor/modules.txt

The initial attempt at creating the necessary bits for Alibaba.

AlibabaCloud: adding alibaba cloud platform

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Adds powerOff ref saving to machine status for more determenistic handling.
Before in case if powerOff task would lag for some reason,
machine deletion would stuck.
Now powerOff task will be checked before destroy task will be created.
By the way, error messages was extended with adding task type there
in order to provide more information in machine events.

Bug 2011668: Improve powerOff task handling during machine deletion on vsphere platform

---

go.mod
go.sum
install/0000_30_machine-api-operator_02_machine.crd.yaml
install/0000_30_machine-api-operator_03_machineset.crd.yaml
pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go
vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
vendor/modules.txt

As part of the Machine Deletion Hooks proposal, we specify that the hook names should be unique with a lifecycle stage. There is no way currently to do that within open api schemas so this must be done using webhooks.
The following PR updates the lifecycle hook checks to check the names for uniqueness and denies any create/update request should the names be duplicated

Bug 2034879: Enforce unique names for lifecycle hooks via webhooks

---

pkg/controller/vsphere/reconciler.go
pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Currently, linkedClone uses by default which cause silent diskGiB parameter ignorance
in case if Snapshot specified or clonee template has snapshots.
Disk size from vm template will be used in this case, which might be undesirable.
This commit changes default behaviour of controller, fullClone will be used by default,
linkedClone should be set explicitly.

Bug 2001008: Change default cloneMode to fullClone.

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

vSphere Network names are not necessarily unique, especially in NSX-T environments which our CI uses. The vSphere Cluster is known from within the reconciler and can be used to isolate the unique network needed to clone machines. 
Tracking in bz1918005 and [SPLAT-345](https://issues.redhat.com/browse/SPLAT-345)

Bug 1918005: Use known vSphere cluster to uniquely identify networks.

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config_test.go
pkg/operator/fixtures/images.json

The image needed to change name to adhere to conventions.
Depends on https://github.com/openshift/release/pull/25351

Bug 2040620: Rename MAPO image

---

go.mod
go.sum
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/operator/sync.go
vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/modules.txt

To include the fix in https://github.com/openshift/library-go/pull/1293 for an issue causing the reconciliation of mutating webhooks to not happen.
Also uses the improved version of `Apply*WebhookConfiguration` with cache.
For more details on the bug: https://bugzilla.redhat.com/show_bug.cgi?id=2041971
Here is an attempt to reproduce the issue with this fix
(the reproduction steps are available on the linked Bugzilla issue):
```
[~] $ oc -n openshift-machine-api get mutatingwebhookconfiguration machine-api -o yaml | grep path
path: /mutate-machine-openshift-io-v1beta1-machine
path: /mutate-machine-openshift-io-v1beta1-machineset
[~] $ oc -n openshift-machine-api get pods
NAME                                          READY   STATUS    RESTARTS   AGE …
```

Bug 2041971: Bump library-go to fix mutating webhook reconcile

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

To enable the changes in https://github.com/openshift/machine-api-provider-aws/pull/16, we need these new permissions within the credentials request.
This has been manually tested and allows the MAPA PR to function as expected

[OCPCLOUD-1381] Add IAM permissions required for AWS Placement Group enhancement

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

To successfully delete placement groups in AWS we have to grant the permission to machine-api-provider-aws.

[OCPCLOUD-1384] Allow to remove ec2 placement groups

---

docs/user/Alerts.md
hack/ci-test.sh
install/0000_90_machine-api-operator_04_alertrules.yaml

By default prometheus metrics in kubernetes contain labels for the pod and instance that created a metric series. If these labels
change during the metric series then it causes a new metric series to be created. When this happens, a long running alert will get reset even if the target of the alert (eg a machine) is the same.
This has deleterious effects when considering things like machines in "Deleting" phase, or missing a Node reference.
This change makes it so that the alert will ignore changes in the pod label during the duration of the alert. It is being added to account for cases where the machine-api-operator pod might be rescheduled and thus its pod name will change. This should allow the alert to persist.
Related to: https://github.com/openshift/machine-api-operator/pull/913

[OCPCLOUD-1260] modify prometheus alerts to ignore pod

---

install/0000_30_machine-api-operator_01_images.configmap.yaml
install/0000_30_machine-api-operator_11_deployment.yaml
install/image-references

Now all image references in the operator use "registry.svc.ci.openshift.org", which has been disabled.
This commit replaces broken image references with working ones from quay.io

Replace broken image references

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

In the machine create workflow we were setting the phase to Provisioning
and then requeuing with the default 30s delay before starting the actual
machine creation. This delay is unnecessary in this case. We let the
default rate limiter handle it instead, which will requeue after 5ms.

Remove 30s wait before creating a machine

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This commit updates the webhook validation, allowing to set "pd-balanced" disk type for GCP platform.

[OCPCLOUD-1419] Add pd-balanced disks support for GCP

---

docs/user/machine-api-operator-overview.md

The current hyperlink for run level points to the CVO
repo version of the document, which no longer exists. This change
is adding the new, correct link to the operator.md file
in the enhancements repo.
Current link:
```
❯ curl -I https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/operators.md#how-do-i-get-added-as-a-special-run-level
HTTP/2 404
```
New Link in this change:
```
❯ curl -I https://github.com/openshift/enhancements/blob/master/dev-guide/cluster-version-operator/dev/operators.md#how-do-i-get-added-as-a-special-run-level
HTTP/2 200
```

Fix broken link to CVO run levels

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go

The forced requeue is redundant as we just updated Status.Phase so the
informer will call us again anyway when it sees the change.
Worse, forcing the requeue causes us to be called before the informer
sees the Status update, meaning we're called with a stale Machine
object. This will cause a storm of Status updates until the informer
catches up.

Don't force a requeue after updating Status.Phase

---

pkg/controller/vsphere/session/session.go
pkg/controller/vsphere/session/session_test.go

Currently there is no request timeout in vCenter client, which might lead to controller blockage in case if vCenter will never respond.

Bug 2083237: Set vCenter client request timeout

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go
pkg/webhooks/machineset_webhook.go
pkg/webhooks/machineset_webhook_test.go

This PR will add validation and defaulting webhook support for PowerVS Platform
Sample Machine Spec can be found [here](https://github.com/openshift/machine-api-provider-powervs/blob/81e0c5c8fc2dc5b2f5ff2e32a37ff673ac9ba407/examples/machine-with-user-data.yaml)

Bug 2094196: Added webhook support for PowerVS platform

---

pkg/controller/machine/controller.go
pkg/controller/machine/controller_test.go
pkg/controller/machine/drain_controller.go
pkg/controller/machine/drain_controller_test.go
pkg/controller/machine/machine_controller_test.go

Introduces new controller which responsible for node draining.
Basically drain logic was moved out to separate controller, running by the same manager. Now machine-controller will block machine deletion until "Drained" condition will not be set to "True" by the "machine-drain-controller". Logic there was mostly untouched and extracted as is, except some events emission was added.
Tested manually on vSphere.

Bug 2082667: Separate controller for the node draining

---

hack/push-updates.sh

Updates revendoring tool:
- move from the `hub` to official github `gh` cli
- introduce an argument for providing pr description
- update MAPI providers repos list
- added workaround for possible default branches discrepancies,
like master vs main

Update revendoring tool

---

install/0000_30_machine-api-operator_00_namespace.yaml

We dropped the run-level label from this namespace back in 4.5
but because of how the cluster-version operator reconciles manifest
labels, dropping a label from the manifest does not remove it from the
in-cluster resource when old clusters are updated into the new
manifest.  This commit uses the approach the cluster-version
operator used to drop its run-level, by setting the value to an
empty string, which the run-level-consuming code treats identically to
an unset label.
This avoids errors about:
...container has runAsNonRoot and image will run as root...
when updating to 4.11 in case the operator deployment  manifest specifically
requests runAsNonRoot: true.

Bug 2101880: operator NS manifest: Set empty openshift.io/run-level

---

pkg/util/windows/helpers.go
pkg/util/windows/helpers_test.go

This change adds a set of helper functions that will be used with
Windows machine deployments. When booting a Windows machine, it is
common for the infrastructure provider to have a method for a Powershell
script to run during boot. This is usually supplied in the user data
metadata associated with a new instance. On Azure and AWS, the script is
required to be wrapped in `<powershell></powershell>` tags, but on GCP
this is not required. The helper functions in this commit will be used
by the providers to help in detecting, adding, and removing these tags.

add utility functions for windows powershell tags

---

FAQ.md
pkg/controller/machineset/delete_policy.go
pkg/controller/machineset/delete_policy_test.go

This maintains backwards compatibilty, but migrates to a new annotation value by default so that we can be congruent with the upstream annotations. By doing so, this means we need fewer carry patches on the cluster autoscaler.
This will need a small docs update, https://docs.openshift.com/container-platform/4.10/machine_management/manually-scaling-machineset.html, CC @jeana-redhat

Migrate delete annotation to match upstream CAPI annotation

---

pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Improves performance in vCenter clusters with thousands of tags and heavy API loads. There should be no reason we need to query for all tags unrelated to a particular install.

Bug 2097153: change ListTags call to ListTagsForCategory

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Avoid setting default values for processor when either int or string values are set

Bug 2107578: Fix while setting default processor value for Power VS platform

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This PR changes the behavior of the operator when users try to remove finalizers. Now we expect to get `{"metadata":{"finalizers":null}}` patch.

Bug 2101736: allow to remove finalizers

---

pkg/controller/machineset/delete_policy.go
pkg/controller/machineset/delete_policy_test.go

this change adds detection to the newest and random delete priority
functions to ensure that we have coverage for the older annotation until
it is removed. also updates the tests to cover a situation where the old
annotation was not detected properly and adds more tests for the new
interactions.

Bug 2109258: add more support for old delete annotation

---

install/0000_30_machine-api-operator_00_namespace.yaml

revert of https://github.com/openshift/machine-api-operator/pull/1031

Bug 2110505: revert: Bug 2101880: operator NS manifest: Set empty openshift.io/run-level

---

pkg/util/windows/helpers.go
pkg/util/windows/helpers_test.go

this change updates the tag identifiers that are used by the WMCO when
creating the secret for the windows boot script. we need to have a
slightly tighter coupling with the WMCO until such time as they drop the
tags from their implementation. once the WMCO removes all the tags, we
should evualte the usefulness of the helper functions and remove or
modify them as necessary. for context, only some of the cloud provider
will need these tags, currently AWS and Azure.

update windows helper functions

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go

Stop passing PowerOn flag and explicitly power on the vm after
successful clone.
If PowerOn flag set to true, vCenter creates additional power on task
after the clone, which we do not know about. Such nuance leads to
possibility of stucking machine in "Provisioned" state
in case if "power on" task did not finish successfully.
This pr adds explicit powering on the machine with saving task reference
and respective checks later. For achieve vm powering on vm separately, during create procedure - exists method also be altered, if machine powered off and sits in "provisioning" phase, it treats as non existed yet.
Additionally powerOn function tries to use datacenter's method "PowerOnMultiVM"
which respects vSphere DRS. If datacenter not provided, function will fallback
to powering on via old …

Bug 2087981: Change "create" sequence with powering on the vm after clone

---

pkg/controller/machine/controller.go
pkg/controller/machine/drain_controller.go

We have observed, with control plane machines, that the drain can get stuck and enter an indefinite deadlock, resulting in the Machine never going away.
The cause of this is the installer pods for the Kube api server (and other static pods on the control plane) trying to reach a later revision. The operators assume they should always be able to upgrade the static pods, even when the node is being drained. They tolerate all taints for the installation process.
Because the drain controller was draining every 20 seconds, what we would see is that the installer pod was created, then terminated, then created, then terminated as KASO fights with the drain controller.
This could happen to other workloads as well, but is more prevalent on the control plane and is causing deadlocks in the rollouts …

Bug 2115308: Ensure failed drains are subject to exponential backoff

---

pkg/util/windows/helpers.go
pkg/util/windows/helpers_test.go

this change adds the function `IsMachineOSWindows` to the windows
utility functions. this logic will repeated in many providers and as
such it makes sense to centralize it, this will also make future changes
easier if the windows labels change.

add a helper function to detect windows os

---

docs/dev/hacking-guide.md

It appears that the incorrect git command was used in the docs. 
I am suggesting the corrected git clone instead of the git checkout
Signed-off-by: Paul Bastide <pbastide@redhat.com>

Change the git command

---

install/0000_30_machine-api-operator_00_namespace.yaml

This reverts commit 401fe30b5a3b4c3c536081639c8ee99edf0fe715.
Reintroducing #1031 since it was reverted in #1044.
This should no longer cause any issues since https://github.com/openshift/cluster-version-operator/pull/804 was merged to solve the issue presented by removing the run-level annotation

Bug 2111972: operator NS manifest: Set empty openshift.io/run-level

---

pkg/controller/vsphere/reconciler.go

This PR enables steal time accounting on
control plane virtual machines.
From the linux commit:
Steal time is the amount of CPU time needed by a guest virtual machine
that is not provided by the host. Steal time occurs when the host
allocates this CPU time elsewhere, for example, to another guest.
Steal time can be enabled by adding the VM configuration option
stealclock.enable = "TRUE". It is supported by VMs that run hardware
version 13 or newer.

OCPBUGS-268: vSphere - enable steal time accounting

---

cmd/machine-api-operator/start.go

Our disruptive tests are really really slow. A large portion of this is the 2 minutes that the leader election must wait before reclaiming the lease when we reschedule the Machine API operator pod several times during the test suite.
I want to force `ReleaseOnCancel` which, is an upstream LeaderElection feature which, when shutting down, once all controllers are stopped, releases the lease. This is tried and tested upstream so I'm not too concerned about enabling it and I think the benefit, speeding up the handover and reducing the amount of time our tests take is significant.
Given this operator only manages deployments and webhooks, there shouldn't be any serious issues even if there are bugs in the implementation.

Release leader election lease when shutting down

---

pkg/webhooks/machine_webhook.go

Now if we want just remove the finalizer, for instance with
```sh
oc patch machines -nopenshift-machine-api machine -p '{"metadata":{"finalizers":null}}' --type=merge
```
in some cases client appends managed fields in the patch, which blocks finalizer removal.
To prevent this we ignore managed fields as they don't affect the result.

Bug 2101736: Ignore managed fields during finalizer removal

---

pkg/controller/vsphere/session/tag_ids_caching_client.go

Adds tag/category name to the caching client log messages to make this messages more explicit and simplify testing.

Add tag and category id to the caching client log messages

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go
pkg/webhooks/machineset_webhook_test.go

We shouldn't allow creating new machines with public IP for disconnected install with Internal publish strategy only. To prevent this confusion we update the message for the error to make it more explicit.

OCPBUGS-519: update error message for disconnected installation validation

---

pkg/operator/sync.go

this change adds an `Exists` toleration to the termination handler, it is being added to help mitigate scenarios where a node is added with taints on it, but where the termination handler will be needed. an example of this is with spot instances that join the cluster with existing taints. in these cases the termination handler will not deploy but should be deployed.

OCPBUGS-1274: add tolerations to termination handler

---

pkg/webhooks/machine_webhook.go

Since https://github.com/openshift/installer/pull/6304 merged, our default webhook that defaults the Azure image resource ID has been broken. This PR updates our defaulting logic to match the format in the installer PR which should resolve the recent Azure minimal webhook test failures we've been seeing

Update default Azure image to use image galleries

---

.ci-operator.yaml
Dockerfile.rhel
pkg/controller/machine/actuator.go
pkg/controller/vsphere/machine_scope.go
pkg/metrics/machinehealthcheck.go
pkg/operator/status.go

Cherry-picked from #1035 
Apply `go fmt` related changes in follow up commit

Updating ose-machine-api-operator images to be consistent with ART

---

pkg/operator/sync.go
pkg/operator/sync_test.go

Since 28853af469d6e3e6c40454de85baa7084d3165c0 we mark the MAO degraded when two workers have not come up (and we ignore this constraint if zero workers are expected), but this will never succeed if exactly one worker has been requested. This was previously an invalid configuration, but since [MGMT-8987](https://issues.redhat.com//browse/MGMT-8987) it is permitted to create a compact cluster with exactly one worker, since the control plane nodes are schedulable.
To handle this case, only remain degraded when we have fewer than two workers *and* all of the expected workers have not yet come up. Leave it to installers to validate which configurations are and are not supported on Day 1.
This does mean that the operator can report that it is degraded even when there are sufficient machines to …

OCPBUGS-2151: Don't degrade when workers not expected

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

I am working on a feature for the AWS provider that will allow it to obtain CPU, Memory, GPU information needed for Autoscaller annotations. This will require new DescribeInstanceTypes permission.
/hold until I have the other PR ready.
I want this PR up so I can use cluster bot to launch cluster with the permission set for testing.

OCPCLOUD-1131: Add DescribeInstanceTypes permission for AWS provider

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This PR adds webhook validations that report warnings if machine provider specs have invalid GroupVersionKind.

Show warnings if provider specs have invalid GroupVersionKind

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go

Manual cherry-pick of https://github.com/openshift/machine-api-operator/pull/1047
Did it manually due to conflicts in the imports section.
respective 4.11 backport: https://github.com/openshift/machine-api-operator/pull/1064

[release-4.10] OCPBUGS-957: Change "create" sequence with powering on the vm after clone

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

In case of multiple network devices in machine's
provider spec it was possible to wrongly use device Backing info
from the previously handled network device instead of returning error
in situation when Network specified for the device does not exist.
This might lead to creating machines which does not comply with the spec.

Bug 2095274: vSphere, fix network existence check for network devices during machine creation

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Despite the fact the documentation says to use `awsproviderconfig.openshift.io` and related APIs for different platforms, it's also possible to use `machine.openshift.io`
This PR updates the webhook to allow this API as well.

Allow to use machine.openshift.io API in provider specs

---

docs/user/TroubleShooting.md

Add a reference to `machine-config-server` so that the documentation readers know in which repository that component resides.

docs: Add a reference to machine-config-server

---

pkg/controller/machineset/machineset_controller_test.go

Currently, when running in CI, machineset tests sometimes fail with timeout error. 
```txt
• Failure in Spec Teardown (AfterEach) [12.059 seconds]
MachineSet Reconciler
/go/src/github.com/openshift/machine-api-operator/pkg/controller/machineset/machineset_controller_test.go:31
Should reconcile a MachineSet [AfterEach]
/go/src/github.com/openshift/machine-api-operator/pkg/controller/machineset/machineset_controller_test.go:77
Timed out after 10.000s.
```
To prevent this we increase the timeout to 20 seconds.

Increase timeout for machineset tests

---

install/0000_30_machine-api-operator_11_deployment.yaml

This PR sets a default container for MAO with a well-defined k8s annotation.

[OCPCLOUD-1708]: Set default container for machine-api-operator

---

pkg/operator/sync.go

The Machine Api's Spot Termination Handler is only compatible with Linux and not with other OSes (e.g. Windows).
Run it only on Nodes running on Linux.

OCPBUGS-5018: machine-api-termination-handler: run DaemonSet only on Linux

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

Prior to this change unknown fields in the porvider spec were ignored silently.
With this change, if the provider spec contains unknown fields it will output a warning e.g.
```
providerSpec.value: Unsupported value: \"randomField-1\": Unknown field (randomField-1) will be ignored
```

Add warning for unknown fields when unmarshaling the provider spec

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

This PR fixes a bug, where `mapi_machinehealthcheck_short_circuit` not properly reconciling causing `MachineHealthCheckUnterminatedShortCircuit`alert to fire. Even in case, where the unhealthy objects don't even exist.
This PR refs to: https://issues.redhat.com/browse/OCPBUGS-4725

[OCPBUGS-4725]: Short circuit misfiring

---

install/image-references

Remove the openstack-machine-controllers image

---

pkg/controller/machinehealthcheck/machinehealthcheck_controller.go

"Unable to retrieve machine from node" is mentioned as `ERROR` but its a warning. It confuses user when it occurs , so better to keep it as warning.
https://issues.redhat.com/browse/OCPBUGS-3275

OCPBUGS-3275: Update machinehealthcheck dropping log from Error to Warning

---

pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go

Follow up for #1114 
In case the drain procedure was performed on a node where kubelet was not operational for some reason, pods on a such node will be stuck in the "Terminating" state and will be never deleted.
If such pods have volumes attached to them, these volumes will never be detached.
For the case when VM was already drained and powered off, but still has attached volumes
we need to attempt forcefully delete pods in "Terminating" state. This will implicitly trigger attach-detach controller to detach disks from the VM.
This patch might help to reduce workloads disruption since vsphere storage driver has known issue for cases when disks was forcefully detached from the vm:
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/e67a2de5c93d4c279231812b3ace6f5f2eb471fa/docs/book/kn …

OCPBUGS-6063: Forcefully delete unevicted pods within vSphere machine deletion procedure

---

install/0000_30_machine-api-operator_09_rbac.yaml

Follow up for https://github.com/openshift/machine-api-operator/pull/1118 with missing permission.
Machine deletion stucks due to vpshere machine controller trying to delete unevicted pods after machine was powered off and drained.

OCPBUGS-6063: Add missed permission for a pod deletion on vsphere platform

---

pkg/operator/config.go
pkg/operator/config_test.go

Handle None and External platform types explicitly. Add extra test for the External platform.

OCPCLOUD-1778: Add None and External platform type explicit handling

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

VCenter does not return 'Cluster' object as a VM ancestor, use VM's host system instead.
Also, this commit introduces using of CachingTagsManager for region/zone tags info obtaining, instead of constructing a non-caching one.

OCPBUGS-7249: Fix zone tag value reconciliation for vSphere machines

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go

Manual cherry-pick with the combination of https://github.com/openshift/machine-api-operator/pull/1114,  https://github.com/openshift/machine-api-operator/pull/1118 and https://github.com/openshift/machine-api-operator/pull/1121.
Did it manually due to bugfix was implemented in three PRs and there was some backward incompatibility within the controller-runtime fake client.
Refs:
- https://github.com/openshift/machine-api-operator/pull/1114 
- https://github.com/openshift/machine-api-operator/pull/1118
- https://github.com/openshift/machine-api-operator/pull/1121

[release-4.12] OCPBUGS-7882: Block machine deletion if extra disks are attached

---

hack/go-build.sh

Currently `git describe` is used to determine the component during OCP build. Since git tags may not be always applied, use environment variables instead.

OCPBUGS-10591: Fix empty component version

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/controller/vsphere/machine_scope.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util.go

Manual cherry-pick of the https://github.com/openshift/machine-api-operator/pull/1120.
Did it manually due to bugfix was implemented in three PRs and there were some conflicts in utils module and incompatability with older gomega versions.
Refs:
- https://github.com/openshift/machine-api-operator/pull/1114
- https://github.com/openshift/machine-api-operator/pull/1118
- https://github.com/openshift/machine-api-operator/pull/1121
- https://github.com/openshift/machine-api-operator/pull/1120

[release-4.11] OCPBUGS-10901: Block machine deletion if extra disks are attached

---

pkg/util/util.go
pkg/util/util_test.go

In the efforts for [MIXEDARCH-129](https://issues.redhat.com//browse/MIXEDARCH-129), we will need to change several cloud providers' actuators to get the kubernetes.io/arch label considered for scaling from zero. The upstream changes introduced by kubernetes/autoscaler/pull/5382 allow us to use an annotation to instruct the autoscaler about the node labels. The actuators will consume the method introduced by this commit to merge the comma-separated list of key-value pairs stored in that annotation with any others the actuators want to add.
cc @elmiko @JoelSpeed @Prashanth684

MIXEDARCH-129: Adds the MergeCommaSeparatedKeyValues method in the util package

---

install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/sync.go

xref: [CCO-321](https://issues.redhat.com//browse/CCO-321)
Value is being read here: https://github.com/openshift/machine-api-provider-azure/pull/55/commits/b317300432a2b37ada7fcd3ece06fba75afd216f#diff-435eecb1d2af40ee96747f88ab71eb2758da989c92f76dcb1f714fc1b300c633R135

CCO-321: Add support for feature-gating specific providers

---

install/0000_90_machine-api-operator_04_alertrules.yaml

We, as a team, don't think this should be a critical alert.

MachineAPIOperatorMetricsCollectionFailing to warning

---

cmd/machine-api-operator/start.go
install/0000_30_machine-api-operator_09_rbac.yaml
pkg/operator/operator.go

noticed in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1423
operator needs to respond to changes in its self-status.

reconcile status when the clusteroperator changes

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go
cmd/vsphere/main.go
pkg/controller/machine/controller_test.go
pkg/controller/machine/machine_controller_suite_test.go
pkg/controller/machinehealthcheck/machinehealthcheck_controller_test.go
pkg/controller/machineset/controller_test.go
pkg/controller/machineset/machineset_controller_suite_test.go
pkg/controller/nodelink/nodelink_controller_test.go
pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/machineset/controller_suite_test.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/util_test.go
pkg/webhooks/v1beta1_suite_test.go

__**tentative**\__
This PR proposes (1) a fix for the MachineSet unit tests suite, affected by data races due to several concurrent executions of the AddToScheme method, (2) the removal of other non-needed executions of the AddToScheme method across other code of the test suite, and (3) the replacement for both the unit tests code and the other code of AddToScheme (deprecated) with Install

Fix data race conditions in unit tests

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Missing permission in credentialsrequest for Azure workload identity needed by MAO.  
OCPBUGS-17919

OCPBUGS-17919: [Azure] MAO Missing DiskEncryptionSet read permissions

---

cmd/machine-healthcheck/main.go
cmd/machineset/main.go
cmd/nodelink-controller/main.go

We were getting error messages from controller-runtime that no logger is set for it. This patch should fix that.

OCPBUGS-17090: Set logger for controller runtime

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

ARO suspects these permissions may only be utilized by the installer and are not needed by MAO. Testing removing the permission with e2e.
EDIT: e2e tests were successful with the permissions removed. Created OCPBUGS-17872 to track.

OCPBUGS-17872: Azure MAO CredentialsRequest contains unnecessary network write permissions

---

pkg/operator/sync.go
pkg/operator/sync_test.go

Don't fail if expected workers is less than 2 since masters are expected to be schedulable in this architecture, which means there will be enough replicas of the operator scheduled.

MGMT-13425: Don't fail when workers not needed

---

pkg/util/machineset/util.go

Currently the individual provider MachineSet actuators each contain string variables and independent implementations of the scale from zero annotations. This configuration is more brittle than having a central module which could be utilized by all the providers.

OCPCLOUD-2138: Add module to work with scale from zero annotations for MachineSet

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Add CloudCredential capability annotation
to the cloud credentials request manifest

OCPVE-778: annotate cloud credentials request

---

pkg/controller/vsphere/reconciler.go

The [original PR](https://github.com/openshift/machine-api-operator/pull/1172) uses a docs URL instead of a KCS one. However, https://github.com/openshift/openshift-docs/pull/63315 changed the location of the documentation.

OCPBUGS-18339: Update reference URL

---

pkg/controller/vsphere/reconciler.go

Manual back port since the docs URL changed in the process of backporting originally.
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>

OCPBUGS-25303: Update reference URL

---

pkg/controller/vsphere/reconciler.go

Manual back port since the docs URL changed in the process of backporting originally.

OCPBUGS-25304: Update Reference URL

---

pkg/controller/machine/controller.go

Adding, in a backwards compatible way, a way for the different actuators to influence the options for the machine controller. Primarily so that we can influence the max concurrent reconciles of the machine controller to handle large scaling events.

OCPBUGS-23544: Add AddWithActuatorOpts to allow overriding Machine controller options

---

pkg/operator/sync.go

Depends on https://github.com/openshift/machine-api-provider-azure/pull/87.
/hold until above is merged
Sets the `max-concurrent-reconciles` flag for the Azure Machine controller to 10. This will be used to improve the performance during large scale ups.

OCPBUGS-23544: Set --max-concurrent-reconciles=10 for Azure machine controller

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This required permission was missed when migrating from roles.

OCPBUGS-27385: Add useExternalIp gcp permission

---

install/0000_30_machine-api-operator_11_deployment.yaml
pkg/operator/sync.go

All openshift operators must include FallbackToLogsOnError to ease debugging.

OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

---

Dockerfile
docs/user/vsphere/tags.md
pkg/controller/vsphere/actuator_test.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/controller/vsphere/session/tag_ids_caching_client.go
pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

This PR intends to address RFE https://issues.redhat.com/browse/RFE-1799. Additional tags are provided by the declaring a slice of tags referenced by their URN ID. This is consistent with how [CAPV ingests additional tags](https://github.com/openshift/cluster-api-provider-vsphere/blob/b21c0ba942580e08352ad6b3170ee17a010a2a00/apis/v1beta1/types.go#L190-L193) for a VM.

SPLAT-1386: reconcile additional tags assigned to machine

---

tools.go

Hello! Running Snyk scans manually in this repo was causing some linting errors due to the tools.go file in the top level of the repo not having build tags. Making this change fixes this and allows scans to be done manually in this repo now. Thanks!

OCPBUGS-26119:  Add build tags to tools.go file to solve linting issues when running Snyk scans

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

ARO team believes these permissions are unnecessary for MAO.  Testing permission removal with e2e.  
[OCPBUGS-29956](https://issues.redhat.com/browse/OCPBUGS-29956) is tracking this.

OCPBUGS-29956: Azure MAO CredentialsRequest Contains Unnecessary virtualMachines/extensions Permissions

---

pkg/util/machineset/util_test.go

Hello, this is a bug fix to update an incorrect passed value for a unit test added i[n a previous PR.](https://github.com/openshift/machine-api-operator/pull/1227) Thanks!

OCPCLOUD-2493: Bug fix in unit test

---

pkg/util/machineset/util.go

Hello! This is a PR to remove the hardcoded value for the GpuType annotation, so that we can use the one passed in from the CAO instead. Thanks!

OCPCLOUD-2501: Update to set GpuType annotation to remove hardcoded value

---

install/0000_30_machine-api-operator_11_deployment.yaml

References:
- [SCC docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html)
- [SCC pinning docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth)

AUTH-482: set required-scc for openshift workloads

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

This commit attempts to recover from a state when instance was cloned the clone taskID was lost. In this state another clone would be issued instead of poweron command.
TaskID can get lost when both machine status cannot be saved and the infrastructure provider restarts.

OCPBUGS-1735: Vsphere: Handle cloned instance with lost taskID

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

As per https://github.com/openshift/api/pull/1897#discussion_r1658841416, we need to add webhook validation to check `placementGroupPartition` must be between 1 and 7

CFE-1065: Add range validation for placementGroupPartition

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Added `Microsoft.Compute/capacityReservationGroups/deploy/action` Permission to default cred Request for users to use capacity reservation with workload Identity.

OCPBUGS-37154: Added Permisions for Azure Capacity Reservation

---

cmd/vsphere/main.go
pkg/controller/machine/controller.go
pkg/controller/machine/machine_controller_test.go

This change adds feature gating to the Machine Controller. The interface is the same as used by the MachineSet controller, where features are passed as flags via `--feature-gates=<name>=<bool>`
This is a breaking change, as we change `AddWithActuator` to expect a feature gate. This means each MAPI provider will need updating to do this.
https://github.com/openshift/machine-api-operator/pull/1269 has an example of the changes required, but the changes from this PR to `cmd/vsphere/main.go` will also be required.

OCPCLOUD-2565: Machine controller feature gating

---

pkg/controller/machine/controller.go
pkg/controller/vsphere/actuator.go

This change updates the message verbs to use %q instead of %s, where appropriate, to properly escape output. This is to ensure potentially malicious input will be properly escaped.

OCPBUGS-31777: Updates message verbs to use %q where appropriate

---

pkg/controller/machineset/delete_policy.go
pkg/controller/machineset/delete_policy_test.go

This PR makes two changes to the way that we calculate the deletion priority in the MachineSet oldest delete policy.
The first is to move from `mustDelete` to `betterDelete`. This change ensures that the other `mustDelete` options always have priority (like having an annotation, or already having a deletion timestamp).
The second change expands the range of values for which the age based priority is actually functional.
With the current logic, the value of `(1.0 - math.Exp(-d.Seconds()/secondsPerTenDays)))` tends to `1` as the age of the machine increases. Currently, when the machine is about 375 days old, this expression equals `1` (thank you floating point numbers) and then the priority just becomes the factor (betterDelete now). This means any machines over this age cannot be …

OCPBUGS-42388: Ensure deletion annotation takes priority and oldestPolicy can distinguish longer ages

---

pkg/controller/machine/controller.go
pkg/controller/machineset/controller.go
pkg/controller/machineset/machineset_controller_test.go

This change updates the Paused condition:
- Use the same reasons across MachineSet and Machine
- If `Status.AuthoritativeAPI` is not set, update the condition message to reflect this.

OCPBUGS-42529: Updates paused condition messages

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

add the webhook validation for the "CapacityReservationID" field of "AwsMachineProviderSpec" in openshift/machine-api-operator so that AWS capacity reservation can be supported.
Supported PR in [openshift/api](https://github.com/openshift/api/pull/1978)

OCPCLOUD-2693: Added the AWS Capacity Reservation Webhook

---

pkg/operator/sync.go

aligned readiness probe to /readyz and liveness to /healthz added explicit timing values for health probes to handle slower response environments like sno during upgrades

OCPBUGS-43481: fix: health probes paths and updated timing

---

cmd/vsphere/main.go

**Changes:**
In 4.16, a change was made to logging configuration. The vSphere machine controller is configured differently from other controllers. This is resulting in verbose log messages being excluded from logs. This PR attempts to make logging configuration consistent with other controllers.

OCPBUGS-41502: vSphere klog initialization preventing verbose log messages

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

Checking history:
```console
$ git --no-pager log -G skipServiceCheck -p --format='commit %h %s' install/0000_30_machine-api-operator_00_credentials-request.yaml | grep 'commit\|skipServiceCheck'
commit 3db6326f stop using beta pre-defined role for compute.targetPools
-    skipServiceCheck: true
commit c4c80c84 GCP CI runs are complaining about APIs not being enabled
+    skipServiceCheck: true
```
But even with 3db6326ffa (#950)'s pivot to roles/compute.admin, we can still get bit by changes [like][1]:
> Upcoming IAM changes for the week of 2024-10-21
> ...
> Compute Engine
> The following permissions have been added to the Compute Admin role (roles/compute.admin):
>
> * `backupdr.backupPlanAssociations.create`
> * `backupdr.backupPlanAssociations.createForComputeInstance`
> ... …

OCPBUGS-43821: install/0000_30_machine-api-operator_00_credentials-request: Set skipServiceCheck again for GCP

---

pkg/operator/status.go
pkg/operator/status_test.go

This PR sets the required SCC explicitly on each workload in openshift-* namespaces. The SCC chosen is the one that the pods are getting admitted with, so no change expected there. This is to protect the pods from getting admitted with a different custom SCC than the one intended.

AUTH-482: set required-scc for openshift workloads 

---

install/0000_30_machine-api-operator_09_rbac.yaml

Added cluster-reader permissions to controlplanemachinesets resource

OCPBUGS-46433: Add cluster-reader to controlplanemachinesets resource

---

pkg/webhooks/machine_webhook.go

Add webhook for fields (providerSpec.iamInstanceProfile.arn, providerSpec.iamInstanceProfile.filters, providerSpec.subnet.arn) that are not working, pre-merge tested works!
```
liuhuali@Lius-MacBook-Pro huali-test % oc create -f ms1.yaml 
Warning: can't use providerSpec.iamInstanceProfile.arn, only providerSpec.iamInstanceProfile.id can be used to reference IAMInstanceProfile
machineset.machine.openshift.io/ci-ln-4li4k6b-76ef8-48lkb-worker-us-west-1ca created
```
```
liuhuali@Lius-MacBook-Pro huali-test % oc create -f ms1.yaml 
Warning: can't use providerSpec.iamInstanceProfile.filters, only providerSpec.iamInstanceProfile.id can be used to reference IAMInstanceProfile
machineset.machine.openshift.io/ci-ln-4li4k6b-76ef8-48lkb-worker-us-west-1ca created
```
```
liuhuali@Lius-MacBook-Pro …
```

OCPBUGS-43608: add webhook for fields that are not working

---

pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go

Manual cherry-pick of #1321.
The main reason it needed human intervention was translating `ptr` calls back to the `pointer` equivalents.

[release-4.14] OCPBUGS-48245: VSphere: Handle cloned instance with lost taskID

---

pkg/operator/operator.go
pkg/operator/operator_test.go

Follow up to #1285.
This PR adds `FeatureGateVSphereHostVMGroupZonal` to the map of features so the command line of the controller pods is set correctly.

SPLAT-1800: vSphere host zonal missing operator feature

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

OCPBUGS-49351
- Added check for max network count

OCPBUGS-49351: Added vSphere check for max networks

---

README.md
docs/dev/hacking-guide.md
docs/user/machine-api-operator-overview.md
install/0000_30_machine-api-operator_00_credentials-request.yaml
install/0000_30_machine-api-operator_01_images.configmap.yaml
install/image-references
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator_test.go

Per thread in [slack](https://redhat-internal.slack.com/archives/CE4UC6AVB/p1738699843095579), oVirt support ended in 4.14 and we no longer wish to reference or be able to install oVirt through MAO.
CC @sdodson

OCPBUGS-51042: Drop oVirt support

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This is to resolve the permission issue when upgraded from 4.11 -> 4.14 .
more context on it [here](https://redhat-internal.slack.com/archives/C04TMSTHUHK/p1738750794938799) 
PTAL when time permits.

OCPBUGS-49413: add image/read permissions

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

This change adds the compute.images.get and getFromFamily to the credentials request for GCP. It is required by MAPG for checking if a disk is UEFI compatible.
See https://github.com/openshift/machine-api-provider-gcp/pull/108

OCPBUGS-51373,OCPBUGS-44671: Updates GCP credentials request

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

add the webhook validation for the "MarketType" API field of "AwsMachineProviderSpec".
Supported PR in https://github.com/openshift/api/pull/2172

OCPCLOUD-2780: Validate aws marketType webhook

---

cmd/machineset/main.go
cmd/vsphere/main.go
pkg/controller/vsphere/reconciler.go
pkg/controller/vsphere/reconciler_test.go
pkg/operator/operator.go
pkg/operator/operator_test.go
pkg/util/testing/testing.go

[SPLAT-2078](https://issues.redhat.com//browse/SPLAT-2078)
- Removed VSphereStaticIPs feature gate
After a feature gate has been GA in an OCP release, we are supposed to clean up feature gate usage in the next release. VSphere static IP support GA'd in 4.16, so the intention is to remove the feature gate as part of 4.19.

SPLAT-2078: Removed VSphereStaticIPs feature gate

---

pkg/webhooks/machine_webhook.go
pkg/webhooks/machine_webhook_test.go

[OCPBUGS-52464](https://issues.redhat.com/browse/OCPBUGS-52464)
- Validate the marketType field value in webhook. 
- Added the unittest

OCPBUGS-52464: webhook to validate marketType field

---

go.mod
go.sum
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/spec.go
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests/types.go
vendor/github.com/openshift-eng/openshift-tests-extension/pkg/ginkgo/util.go
vendor/modules.txt

[SPLAT-2118](https://issues.redhat.com//browse/SPLAT-2118)
- Updated openshift-tests-extensions dep to get new vendor filtering logic for external tests.
- https://github.com/openshift-eng/openshift-tests-extension/pull/29
- https://github.com/openshift/origin/pull/29579

SPLAT-2118: Update tests-extensions to pick up new vendor filtering

---

pkg/controller/nodelink/nodelink_controller.go

Use patch to apply machine's nodeRef, to retain the `.status.synchronizedGeneration` field previously set by the migration/sync controllers. 
---
I found an conflicting issue between the migration/sync controllers, the nodelink controller and the CPMSO.
A cluster with MachineAPIMigration=true is installed
- The installer creates control plane machines, which gets registered with the cluster
- The installer applies/creates control plane machines objects in the cluster
- The migration controller gets notified about a machine event, and reconciles, finds the .status.authoritativeAPI is empty and propagates the value from .spec.authoritativeAPI to it [a] (logs here)
In the meanwhile the CPMSO hasn't started up yet (see logs here) so no owner reference of the CPMSO is set on the control plane …

OCPBUGS-55025: fix: nodelink use patch to apply machine's nodeRef

---

test/e2e/vsphere/machines.go
test/e2e/vsphere/multi-nic.go

[SPLAT-2180](https://issues.redhat.com//browse/SPLAT-2180)
- Added `Conformance` label to e2e tests (for future way)
- Added `[Suite:openshift/conformance/parallel]` to e2e tests for legacy (current) technique
Currently when nightlies run, the new openshift test extensions are being seen, but not ran.  Adding the `Conformance` label to the tests so they are included in the parallel suite.
openshift-tests-ext has a way for adding your files to parent suites; however, this is not functional at this time.  
This PR will need to be backported to 4.19

SPLAT-2180: Added conformance label

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

- Adds compute.images.useReadOnly, which is required for provisioning additional disks.

OCPBUGS-55083: Updates GCP CredentialsRequest

---

pkg/controller/machineset/controller.go

This change updates the error log to rely on the machineSetCopy, rather than the machineSet passed to be updated.
This is because the machineSet may be nil if the update fails, due to the get at the end of updateMachineSetStatus.

OCPBUGS-55461: Fix updateMachineSetStatus nil pointer

---

test/e2e/vsphere/machines.go
test/e2e/vsphere/multi-nic.go

[OCPBUGS-55424](https://issues.redhat.com//browse/OCPBUGS-55424)
- Added check for multi network config before running test
- Updated multi network tests to have apigroup label
- Revert https://github.com/openshift/machine-api-operator/pull/1359
- https://github.com/openshift/machine-api-operator/pull/1360

OCPBUGS-55424: Added skip for when config not multi nic

---

pkg/controller/machine/controller_test.go
pkg/controller/machine/drain_controller.go
pkg/controller/machineset/status.go

In a similar vein of https://github.com/openshift/machine-api-operator/pull/1352
Use patch to apply machine's status, to retain the .status.synchronizedGeneration field previously set by the migration/sync controllers.

OCPBUGS-55720: fix: use patch for machine/machineset status

---

pkg/controller/machine/controller_test.go
pkg/controller/machine/drain_controller.go
pkg/controller/machineset/status.go

Manual backport of https://github.com/openshift/machine-api-operator/pull/1362
Superseeds https://github.com/openshift/machine-api-operator/pull/1364

[release-4.19] OCPBUGS-55706: fix: use patch for machine/machineset status

---

test/e2e/util.go
test/e2e/vsphere/machines.go
test/e2e/vsphere/multi-nic.go
test/e2e/vsphere/util.go

[OCPBUGS-55461](https://issues.redhat.com/browse/OCPBUGS-55461)
- Changed machineset tests to run in serial suite instead of parallel (both data disk and nic tests)
- Added taints to machinesets to prevent unnecessary pod scheduling
- Modified NIC machineset test to not look at all VMs in the failure domain, but rather focus on ones with the cluster's tag on them.
- Included following changes from past reverts:
- Added check for multi network config before running test
- Updated multi network tests to have apigroup label
- Added [Suite:openshift/conformance/parallel] to e2e tests for legacy (current) technique
- Added Conformance label to e2e tests (for future way)
This PR is fixing issues found via this bug.  There were several issues found.
- Panic when interacting with migration TP …

OCPBUGS-55461: Changed machineset tests to be serial

---

install/0000_30_machine-api-operator_00_credentials-request.yaml

- In **[AWS official doc](https://docs.aws.amazon.com/ebs/latest/userguide/ebs-encryption-requirements.html)** the ebs volume kms encryption needs the follow permissions ->
```console
- kms:CreateGrant
- kms:Decrypt
- kms:DescribeKey
- kms:GenerateDataKeyWithoutPlainText
- kms:ReEncrypt
```
Using customer kms key create machine in the local zone failed caused by missed `kms:ReEncrypt` permission.

OCPBUGS-56159: correct aws kms permissions

---

test/e2e/util.go
test/e2e/vsphere/hostzonal.go
test/e2e/vsphere/util.go

The two new checks are:
- Does the virtual machines created belong in the
correct vm-host group of type VirtualMachine
- Does the nodes have the correct topology labels
for their location within vSphere based on tags
- https://github.com/openshift/enhancements/pull/1677
- https://github.com/openshift/installer/pull/8873
- https://github.com/openshift/client-go/pull/294
- https://github.com/openshift/library-go/pull/1782
- https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/325
- https://github.com/openshift/machine-api-operator/pull/1285
- https://github.com/openshift/api/pull/1999

SPLAT-2082: Create e2e for vSphere vm-host zonal feature

---

test/e2e/vsphere/multi-nic.go

OCPBUGS-57018
- Fixed checks relating to length of arrays
- Added skip for when no machines / UPI scenario

OCPBUGS-57018: Fixed test logic for UPI scenario

---

pkg/operator/sync.go

Depends on https://github.com/openshift/machine-api-provider-gcp/pull/124
Enables the new max-concurrent-reconciles flag on GCP to speed up processing of deep reconcile queues

OCPBUGS-59376: Enabled 10 concurrent reconciles on GCP

---

pkg/operator/sync.go

Depends on https://github.com/openshift/machine-api-provider-gcp/pull/125
Enables the new max-concurrent-reconciles flag on GCP to speed up processing of deep reconcile queues

[release-4.19] OCPBUGS-59386: Enabled 10 concurrent reconciles on GCP
